### ISSUE TITLE
Could You make a new branch for the v3 rewrite? 

### ISSUE THREAD

**Issue by Minuga-RC** [XengShi/materialYouNewTab#105]
@XengShi could you make a new branch in the repo so I can open a pull req to that.
I just finished the v3-rewrite

**Comment by XengShi** [comment]
Okayy

**Comment by Minuga-RC** [comment]
umm did u make the branch I cant really see it rn @XengShi

**Comment by itz-rj-here** [comment]
https://github.com/XengShi/materialYouNewTab/tree/v3

**Comment by Minuga-RC** [comment]
> https://github.com/XengShi/materialYouNewTab/tree/v3

Yea ik I'm waiting for him to merge my new PR to it

**Comment by prem-k-r** [comment]
@XengShi please close
