### ISSUE TITLE
make a new release from recent fixes (beta)

### ISSUE THREAD

**Issue by fisforfaheem** [XengShi/materialYouNewTab#106]
This will help better for feedback

**Comment by itz-rj-here** [comment]
@XengShi @prem12321kumar

**Comment by itz-rj-here** [comment]
Currently @Minuga-RC is rewriting the project, but we will try to release a stable or a beta version as you requested. Thanks

**Comment by Minuga-RC** [comment]
You can beta test it over in my repo
https://github.com/Minuga-RC/BetterMaterialYouNewTab/releases/tag/v3

**Comment by prem12321kumar** [comment]
@fisforfaheem available now

**Comment by fisforfaheem** [comment]
Unable to use it it's just source code

**Comment by Minuga-RC** [comment]
> Unable to use it it's just source code
Usable version is in release tab https://github.com/Minuga-RC/BetterMaterialYouNewTab/releases/tag/v3.1.5

**Comment by Minuga-RC** [comment]
![image](https://github.com/user-attachments/assets/8684b2d5-cee7-45bc-b923-8c07e690b8bb)
download this not the source code.zip

**Comment by prem-k-r** [comment]
@XengShi please close
