### ISSUE TITLE
Darker hour part of digital clock

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#116]
A look of analog and digital clocks could be unified by setting a darker color to the hour part of the time. The analog clock has a darker, smaller hand so that it will be equivalent. The digital clock is boring, so this could help with this.

**Comment by prem12321kumar** [comment]
Working on it? Should I take a look? 
What about colon symbol color?

**Comment by ceskyDJ** [comment]
No, I' not working on it. It's just an idea. I can make a quick preview. A colon could be tuned, too, it sounds like a good move.

**Comment by prem12321kumar** [comment]
preview, still lots to fix

https://github.com/user-attachments/assets/39d758a6-3115-448f-9fe5-17d0cfea851d

**Comment by prem12321kumar** [comment]
#107 done

**Comment by ceskyDJ** [comment]
Nice! Thanks ❤️.

**Comment by prem12321kumar** [comment]
> #107 done


https://github.com/user-attachments/assets/2601c45a-c38e-4c54-834c-57f99c10e387

**Comment by prem12321kumar** [comment]
> Nice! Thanks ❤️.

My pleasure! 
You can try it out at https://prem12321kumar.github.io/materialYouNewTab/

Or can download it from https://github.com/prem12321kumar/materialYouNewTab/releases/tag/v2.71828-beta

**Comment by ceskyDJ** [comment]
I've already tried it. It's good.

**Comment by prem12321kumar** [comment]
Maybe close issue?

**Comment by ceskyDJ** [comment]
If course I'm deeply sorry.

**Comment by prem12321kumar** [comment]
> If course I'm deeply sorry.

No worries
