### ISSUE TITLE
Change page/tab icon according to selected color theme

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#119]
Now, there is always a blue icon (use the color of the default color theme). I think a better approach is to switch icons according to the selected color theme. So, when I switch to green, the icon also changes to a green variant.

**Comment by itz-rj-here** [comment]
@ceskyDJ you mean this?
![image](https://github.com/user-attachments/assets/6ca75ed3-297a-47bc-9d1d-70d8bdb3ade1)

**Comment by ceskyDJ** [comment]
> @ceskyDJ you mean this?
> ![image](https://github.com/user-attachments/assets/6ca75ed3-297a-47bc-9d1d-70d8bdb3ade1)
> 

Yes, I mean exactly that.

**Comment by itz-rj-here** [comment]
> > @ceskyDJ you mean this?
> > ![image](https://private-user-images.githubusercontent.com/86042583/382558204-6ca75ed3-297a-47bc-9d1d-70d8bdb3ade1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzU2MDYsIm5iZiI6MTczMDYzNTMwNiwicGF0aCI6Ii84NjA0MjU4My8zODI1NTgyMDQtNmNhNzVlZDMtMjk3YS00N2JjLTlkMWQtNzBkOGJkYjNhZGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEyMDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNmEyYWU1NzVmMTllNzQyZTk1MGMyMDRhYjlkMmU4MGYxNDFhMzFmNjBmNzg1ODVhNzZlOWI1NWIwZDNjNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eqEdmeISy-wNGhb3d6COlrQdPAEf4ctp4QoVYa5jRfI)
> 
> Yes, I mean exactly that.

But its a logo not something else.
but as you said i will try to look into it if there is any way to add this feature after my exams.

**Comment by ceskyDJ** [comment]
There is a solution for it. Some web pages change icons, e.g., as a notification appears, so it shouldn't be a problem to implement it.

**Comment by prem-k-r** [comment]
Yes, it's possible
Most likely to achieve this, we need to set things up in the background.js so that whenever the user switches to a new theme, the extension detects this change and updates the icon accordingly.

**Comment by itz-rj-here** [comment]
> Yes, it's possible Most likely to achieve this, we need to set things up in the background.js so that whenever the user switches to a new theme, the extension detects this change and updates the icon accordingly.

Oo. I can understand now. Ok it's on you @prem-k-r. Cuz as I said I have ongoing exams to do.

**Comment by itz-rj-here** [comment]
Can we like list all the feature request in one issue?..
Ok let me create one. I have some ideas too. let me create one.

**Comment by prem-k-r** [comment]
> > Yes, it's possible Most likely to achieve this, we need to set things up in the background.js so that whenever the user switches to a new theme, the extension detects this change and updates the icon accordingly.
> 
> Oo. I can understand now. Ok it's on you @prem-k-r. Cuz as I said I have ongoing exams to do.

I'll try it later with dummy icons. 
Meanwhile others can also try.
