### ISSUE TITLE
Unexpected behavior of the hour hand at 12 am on analog mode

### ISSUE THREAD

**Issue by prem-k-r** [XengShi/materialYouNewTab#123]
Only when time is 12:00 AM
and pm(?)

https://github.com/user-attachments/assets/414681c5-7512-44c7-8739-6c953ad5988f

**Comment by prem12321kumar** [comment]
According to ChatGPT, modifying the last if-else block of the updateanalogclock function could solve this issue. Below is the code:

// Handle hour hand rotation only on the minute mark
    if (initialMinutes === 0 && initialSeconds === 0 && (initialHours === 0 || initialHours === 12)) {
        document.getElementById("hour").style.transition = "transform 1s ease";
        document.getElementById("hour").style.transform = ``` `rotate(361deg)` ```;
        hourreset = true;
    } else if (initialMinutes === 0 || !hourreset) {
        document.getElementById("hour").style.transition = "transform 1s ease";
        document.getElementById("hour").style.transform = ``` `rotate(${cumulativeHourRotation}deg)` ```;
    }

Could someone please review the logic and make any necessary adjustments to ensure it functions correctly?

**Comment by itz-rj-here** [comment]
@Minuga-RC can you check it
