### ISSUE TITLE
add bookmarks to shortcuts

### ISSUE THREAD

**Issue by showthesunli** [XengShi/materialYouNewTab#129]
I want  add `chrome://bookmarks/` in shortcuts, but it automatically adds `https` to the beginning of the  link.

![image](https://github.com/user-attachments/assets/96366d2a-8b42-4ccd-bc32-ad0688c95ac9)

![image](https://github.com/user-attachments/assets/aa0d39e9-5737-40ef-84cd-62ef0341b023)

**Comment by prem-k-r** [comment]
I tried to fix it by removing the automatic addition of https:// for internal pages, but when testing in Chrome, I'm getting the following error: "Not allowed to load local resource: chrome://bookmarks/."

I Googled and found out that we cannot navigate to internal pages (such as chrome://bookmarks/) directly from any Chrome extension because of security restrictions and privacy reasons. The same applies to edge://, brave://, and opera://. While direct access is not possible, there might be indirect methods to achieve similar functionality, though I'm not certain what they are.

**Comment by showthesunli** [comment]
> I attempted to resolve it by disabling the automatic addition of https:// for internal pages, but upon testing in Chrome, I encountered the following error: "Not allowed to load local resource: chrome://bookmarks/."
>
> I searched online and discovered that it's not possible to directly navigate to internal pages (such as chrome://bookmarks/) from any Chrome extension due to security constraints and privacy concerns. This rule applies to edge://, brave://, and opera:// as well. Although direct access isn't feasible, there could be alternative methods to accomplish a similar outcome, but I'm unsure of what those might be.

I am not aware of Chrome's restrictions on extensions. I think this issue should be closed.

**Comment by prem-k-r** [comment]
> > I attempted to resolve it by disabling the automatic addition of https:// for internal pages, but upon testing in Chrome, I encountered the following error: "Not allowed to load local resource: chrome://bookmarks/."
> > I searched online and discovered that it's not possible to directly navigate to internal pages (such as chrome://bookmarks/) from any Chrome extension due to security constraints and privacy concerns. This rule applies to edge://, brave://, and opera:// as well. Although direct access isn't feasible, there could be alternative methods to accomplish a similar outcome, but I'm unsure of what those might be.
> 
> I am not aware of Chrome's restrictions on extensions. I think this issue should be closed.

nah, leave it open, its should be possible some other way.

**Comment by itz-rj-here** [comment]
@showthesunli the bookmark has been inncluded to the extention. Have fun with it. #349

**Comment by prem-k-r** [comment]
I see Claude in shortcuts.. one user asked in chrome web store review too.. should we add it normally?

**Comment by itz-rj-here** [comment]
> I see Claude in shortcuts.. one user asked in chrome web store review too.. should we add it normally?

Ask XengShi first
