### ISSUE TITLE
Add support for custom search engines

### ISSUE THREAD

**Issue by theoneand33** [XengShi/materialYouNewTab#13]

**Comment by itz-rj-here** [comment]
Already Added.

**Comment by prem-k-r** [comment]
It has been added. Not custom though, but multiple search engines.

**Comment by prem-k-r** [comment]
@XengShi please check if this issue can be closed.

**Comment by itz-rj-here** [comment]
@XengShi

**Comment by anynomal** [comment]
> It has been added. **Not custom though**, but multiple search engines.

Then it \[the user's request] hasn't been added. It's easy enough to add an additional setting like the shortcuts one for users to add their own search schema.

**Comment by itz-rj-here** [comment]
> > It has been added. **Not custom though**, but multiple search engines.
> 
> Then it [the user's request] hasn't been added. It's easy enough to add an additional setting like the shortcuts one for users to add their own search schema.

Currently we have no plan about it. Cause we need to check how can we add it. Cause there are search suggestion and voice search things. So we may need time to include it.

Don't worry about it. Soon it will be added.

**Comment by prem-k-r** [comment]
> > It has been added. **Not custom though**, but multiple search engines.
> 
> Then it [the user's request] hasn't been added. It's easy enough to add an additional setting like the shortcuts one for users to add their own search schema.

Yeah, it's in the future plan. Edit shortcuts-like page for both Search engines and AI tools. 
You can try implementing it if you want.

**Comment by anynomal** [comment]
> Currently we have no plan about it. Cause we need to check how can we add it. Cause there are search suggestion and voice search things. So we may need time to include it.

That's fine, and I also saw this a few minutes later - #217 - so I can see that it's something that you and the author have expressed interest in 👍  that's great. 

However, my main issue is with dismissing _this_ user's request that came in before the above or any discussion about it. 
Consider: this is an actual user, and you waved away the request without further consideration. 

That is all.

**Comment by prem-k-r** [comment]
Hi @theoneand33 , if you are using Chromium browser, you can use any search engine defined in the browser settings. You can download it from the Chrome Web Store. 

A custom search engine fetaure can be added in the future.

**Comment by theoneand33** [comment]
> Hi @theoneand33 , if you are using Chromium browser, you can use any search engine defined in the browser settings. You can download it from the Chrome Web Store. 
> 
> A custom search engine fetaure can be added in the future.

BTW using firefox based browser Zen browser but it has been added
