### ISSUE TITLE
Buttons for choosing search engines aren't clickable outside of a checkbox input

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#134]
If I click elsewhere than the checkbox input's circle of the search engine select section, the button doesn't react to my click. It should be more responsive, so it reacts anywhere on my clicks.

See the video for a detailed understanding:
https://www.awesomescreenshot.com/video/33214102?key=cbde51a6e8b43630d2c9c678313aef96

**Comment by prem-k-r** [comment]
Merged, please close

**Comment by ceskyDJ** [comment]
I've tried it, and it is working. One thing that needs to be fixed is that it doesn't change a mouse cursor on the hover effect (like the checkbox input circle does). It may not be very clear to some users. I'd add a `cursor: pointer;` to the whole button.

**Comment by prem-k-r** [comment]
Please add it if you can, otherwise, I can try it tomorrow.

**Comment by ceskyDJ** [comment]
@prem-k-r, could you please add it? I don't have so much time for it. You can add a `Closes #134` to the issue description (as I noted in #133); it'll close this after merging the pull request.

**Comment by prem-k-r** [comment]
Okay

**Comment by itz-rj-here** [comment]
> I've tried it, and it is working. One thing that needs to be fixed is that it doesn't change a mouse cursor on the hover effect (like the checkbox input circle does). It may not be very clear to some users. I'd add a `cursor: pointer;` to the whole button.

I will do that later.

**Comment by prem-k-r** [comment]
Closes #134

**Comment by prem-k-r** [comment]
~~Closes #134~~
I understand now automatic closure. I'll do it from now on. 

Please close this issue as completed manually @ceskyDJ @XengShi

**Comment by ceskyDJ** [comment]
> You can add a Closes #134 to the issue description (as I noted in #133); it'll close this after merging the pull request.

Oh, I'm so sorry for confusion. I don't know what I have swapped it.
