### ISSUE TITLE
Save custom shortcuts' favicon locally to load in offline too.

### ISSUE THREAD

**Issue by prem-k-r** [XengShi/materialYouNewTab#135]
To be clear what I mean, following are the steps to reproduce:
-Add a custom shortcut.
-Disconnect internet
-Refresh or open new tab
-Now look at the icon of the custom shortcut

Or simply open chrome when not connected to internet

**Comment by prem-k-r** [comment]
![image](https://github.com/user-attachments/assets/c4582907-6634-45ac-be17-923720648849)
pppp

**Comment by itz-rj-here** [comment]
Hmm thats not good tho. But also the weather will not work too. Without the internet connection.

**Comment by prem-k-r** [comment]
> Hmm thats not good tho. But also the weather will not work too. Without the internet connection.

Weather is fine, they have default fallback text and icon too. 
But for this shortcuts if we could save them like bookmark icons in chrome

**Comment by mekanhaji** [comment]
I suggest using the favicon stored in the browser. 
Learn more about it here : https://developer.chrome.com/docs/extensions/how-to/ui/favicons

Keep in mind that the extension may require additional permissions to access this feature.

**Comment by itz-rj-here** [comment]
> I suggest using the favicon stored in the browser. 
> Learn more about it here : https://developer.chrome.com/docs/extensions/how-to/ui/favicons
> 
> Keep in mind that the extension may require additional permissions to access this feature.

@prem-k-r

**Comment by prem-k-r** [comment]
> I suggest using the favicon stored in the browser. Learn more about it here : [developer.chrome.com/docs/extensions/how-to/ui/favicons](https://developer.chrome.com/docs/extensions/how-to/ui/favicons)
> 
> Keep in mind that the extension may require additional permissions to access this feature.

Thanks for the info. we do want to avoid extra permissions.. for now I'm happy with current workaround to show offline icon lol

**Comment by itz-rj-here** [comment]
> > I suggest using the favicon stored in the browser. Learn more about it here : [developer.chrome.com/docs/extensions/how-to/ui/favicons](https://developer.chrome.com/docs/extensions/how-to/ui/favicons)
> > 
> > Keep in mind that the extension may require additional permissions to access this feature.
> 
> Thanks for the info. we do want to avoid extra permissions.. for now I'm happy with current workaround to show offline icon lol

I think your idea is better. Cause as users add shortcuts, the more icons will be stored in the local. So i say the current one is actually better.
