### ISSUE TITLE
Add Google Account Button

### ISSUE THREAD

**Issue by Nobody9512** [XengShi/materialYouNewTab#137]
Hello! First of all, thank you for the amazing theme. I noticed that the current theme does not include a Google account button (as shown in the screenshot). Adding this feature would make my workflow much more convenient, as it would allow quicker access to my Google account settings directly from the theme.

Could you consider adding the Google account button to the theme? This small addition would significantly improve usability. Thank you for your consideration!
![Screenshot_20241104_101617](https://github.com/user-attachments/assets/d6f4e58d-83f0-466d-89f4-ac0ae9f071e6)

**Comment by itz-rj-here** [comment]
@prem-k-r i would like to know something for you. Is it possible to add an account button on the extention? Like as i know we may need to add an authorization system to add the account button actually. What do you think?

**Comment by prem-k-r** [comment]
It's difficult to implement without using the Google API and all.
However, a workaround could be adding an icon at the top right that redirects to https://myaccount.google.com/ when clicked.

**Comment by XengShi** [comment]
> I don't think it's possible to implement it without Google API integration and all.
> However, a workaround could be adding an icon at the top right that redirects to https://accounts.google.com/SignOutOptions when clicked.

I think it can be implemented like shortcuts that we already have.
We only need to make all the shortcuts for those Google sites then design them to look like Google's

**Comment by prem-k-r** [comment]
> > I don't think it's possible to implement it without Google API integration and all.
> > However, a workaround could be adding an icon at the top right that redirects to https://accounts.google.com/SignOutOptions when clicked.
> 
> I think it can be implemented like shortcuts that we already have. We only need to make all the shortcuts for those Google sites then design them to look like Google's

I was referring to the Google account button as mentioned in the issue.

Creating Google app shortcuts that expand from a 9-dot icon to show a list of apps can definitely be implemented like as you said.

**Comment by itz-rj-here** [comment]
> > > I don't think it's possible to implement it without Google API integration and all.
> > > However, a workaround could be adding an icon at the top right that redirects to https://accounts.google.com/SignOutOptions when clicked.
> > 
> > 
> > I think it can be implemented like shortcuts that we already have. We only need to make all the shortcuts for those Google sites then design them to look like Google's
> 
> I was referring to the Google account button as mentioned in the issue.
> 
> Creating Google app shortcuts that expand from a 9-dot icon to show a list of apps can definitely be implemented like as you said.

The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.

**Comment by prem-k-r** [comment]
> The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.

I wouldn't recommend adding such options in the menu since the user might be switching Google accounts. Instead, I suggest adding an icon to display a list of Google apps, followed by an account icon that redirects to the mentioned link when clicked. Additionally, we could include a toggle in the menu to show or hide both icons at once.

**Comment by itz-rj-here** [comment]
> > The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.
> 
> I wouldn't recommend adding such options in the menu since the user might be switching Google accounts. Instead, I suggest 
> - adding an icon to display a list of Google apps,
> - followed by an account icon that redirects to the mentioned link when clicked.
> - Additionally, we could include a toggle in the menu to show or hide both icons at once.

Can you give me a concept picture of your idea too for more clarification?

**Comment by prem-k-r** [comment]
> Do you mean copying this full google apps section?
> 
> ![image](https://private-user-images.githubusercontent.com/86042583/384695917-595abd52-4c8f-4717-acf3-0c7672ebd4df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg0MjUsIm5iZiI6MTczMTI0ODEyNSwicGF0aCI6Ii84NjA0MjU4My8zODQ2OTU5MTctNTk1YWJkNTItNGM4Zi00NzE3LWFjZjMtMGM3NjcyZWJkNGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDQ3YzVmN2JjMTYzMjg0OTRjMjgxYzhiZDJmM2IwOTJlOTliYmVjMjk4ODZlNmY2NWExMGQ0ZDhkNTE4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7qwwaqhSlp-sNhdn1I25j9boCfCjT6bMgRxTV6rGhaU)

Yeah, similar to this. Only most used one. However I was thinking of account icon to be added first. Perhaps XengShi want Google apps too, that's why.

**Comment by prem-k-r** [comment]
> > > The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.
> > 
> > 
> > I wouldn't recommend adding such options in the menu since the user might be switching Google accounts. Instead, I suggest
> > 
> > * adding an icon to display a list of Google apps,
> > * followed by an account icon that redirects to the mentioned link when clicked.
> > * Additionally, we could include a toggle in the menu to show or hide both icons at once.
> 
> Can you give me a concept picture of your idea too for more clarification?

9 dots icon or something else 
Account icon
Similar to in Google.com

**Comment by itz-rj-here** [comment]
> > > > The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.
> > > 
> > > 
> > > I wouldn't recommend adding such options in the menu since the user might be switching Google accounts. Instead, I suggest
> > > 
> > > * adding an icon to display a list of Google apps,
> > > * followed by an account icon that redirects to the mentioned link when clicked.
> > > * Additionally, we could include a toggle in the menu to show or hide both icons at once.
> > 
> > 
> > Can you give me a concept picture of your idea too for more clarification?
> 
> 9 dots icon or something else Account icon Similar to in Google.com

How it is possible to add the profile picture as a icon on the google apps?
let me ask gpt if he got any answers.

**Comment by prem-k-r** [comment]
> > > > > The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.
> > > > 
> > > > 
> > > > I wouldn't recommend adding such options in the menu since the user might be switching Google accounts. Instead, I suggest
> > > > 
> > > > * adding an icon to display a list of Google apps,
> > > > * followed by an account icon that redirects to the mentioned link when clicked.
> > > > * Additionally, we could include a toggle in the menu to show or hide both icons at once.
> > > 
> > > 
> > > Can you give me a concept picture of your idea too for more clarification?
> > 
> > 
> > 9 dots icon or something else Account icon Similar to in Google.com
> 
> How it is possible to add the profile picture as a icon on the google apps? let me ask gpt if he got any answers.

Need api integration for it.. that's why a black account symbol

**Comment by itz-rj-here** [comment]
> > > > > > The 9-dot icon can be easily added, but adding an account button may be hard to do. We may only make the UI of the account button. Also adding an option to the menu to add a profile picture, name, and email. Or if possible, using the email, we can add the name and profile picture automatically. Nothing more we can do.
> > > > > 
> > > > > 
> > > > > I wouldn't recommend adding such options in the menu since the user might be switching Google accounts. Instead, I suggest
> > > > > 
> > > > > * adding an icon to display a list of Google apps,
> > > > > * followed by an account icon that redirects to the mentioned link when clicked.
> > > > > * Additionally, we could include a toggle in the menu to show or hide both icons at once.
> > > > 
> > > > 
> > > > Can you give me a concept picture of your idea too for more clarification?
> > > 
> > > 
> > > 9 dots icon or something else Account icon Similar to in Google.com
> > 
> > 
> > How it is possible to add the profile picture as a icon on the google apps? let me ask gpt if he got any answers.
> 
> Need api integration for it.. that's why a black account symbol

Okay for now let me try to make the google apps thingy and what about the tooltip thing? Could you manage to add it on the location? #96

**Comment by prem-k-r** [comment]
![material-symbols--account-box](https://github.com/user-attachments/assets/6c5372e4-7f70-4027-96ec-a07c462066bb)
Or
![material-symbols--account-circle](https://github.com/user-attachments/assets/be20d390-a75c-4889-8af9-9a67be2a671c)

**Comment by itz-rj-here** [comment]
The 2nd one is better.

**Comment by prem-k-r** [comment]
> Okay for now let me try to make the google apps thingy and what about the tooltip thing? Could you manage to add it on the location? #96

I haven't tried again

**Comment by itz-rj-here** [comment]
> > Okay for now let me try to make the google apps thingy and what about the tooltip thing? Could you manage to add it on the location? #96
> 
> I haven't tried again

Can anyone code me this 9 dots icon thingy as svg code please :)

**Comment by prem-k-r** [comment]
@itz-rj-here 
https://icon-sets.iconify.design/
Check here

**Comment by prem-k-r** [comment]
<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
	<path fill="currentColor" d="M6 20q-.825 0-1.412-.587T4 18t.588-1.412T6 16t1.413.588T8 18t-.587 1.413T6 20m6 0q-.825 0-1.412-.587T10 18t.588-1.412T12 16t1.413.588T14 18t-.587 1.413T12 20m6 0q-.825 0-1.412-.587T16 18t.588-1.412T18 16t1.413.588T20 18t-.587 1.413T18 20M6 14q-.825 0-1.412-.587T4 12t.588-1.412T6 10t1.413.588T8 12t-.587 1.413T6 14m6 0q-.825 0-1.412-.587T10 12t.588-1.412T12 10t1.413.588T14 12t-.587 1.413T12 14m6 0q-.825 0-1.412-.587T16 12t.588-1.412T18 10t1.413.588T20 12t-.587 1.413T18 14M6 8q-.825 0-1.412-.587T4 6t.588-1.412T6 4t1.413.588T8 6t-.587 1.413T6 8m6 0q-.825 0-1.412-.587T10 6t.588-1.412T12 4t1.413.588T14 6t-.587 1.413T12 8m6 0q-.825 0-1.412-.587T16 6t.588-1.412T18 4t1.413.588T20 6t-.587 1.413T18 8" />
</svg>

**Comment by prem-k-r** [comment]
<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
	<path fill="currentColor" d="M6 20q-.825 0-1.412-.587T4 18t.588-1.412T6 16t1.413.588T8 18t-.587 1.413T6 20m6 0q-.825 0-1.412-.587T10 18t.588-1.412T12 16t1.413.588T14 18t-.587 1.413T12 20m6 0q-.825 0-1.412-.587T16 18t.588-1.412T18 16t1.413.588T20 18t-.587 1.413T18 20M6 14q-.825 0-1.412-.587T4 12t.588-1.412T6 10t1.413.588T8 12t-.587 1.413T6 14m6 0q-.825 0-1.412-.587T10 12t.588-1.412T12 10t1.413.588T14 12t-.587 1.413T12 14m6 0q-.825 0-1.412-.587T16 12t.588-1.412T18 10t1.413.588T20 12t-.587 1.413T18 14M6 8q-.825 0-1.412-.587T4 6t.588-1.412T6 4t1.413.588T8 6t-.587 1.413T6 8m6 0q-.825 0-1.412-.587T10 6t.588-1.412T12 4t1.413.588T14 6t-.587 1.413T12 8m6 0q-.825 0-1.412-.587T16 6t.588-1.412T18 4t1.413.588T20 6t-.587 1.413T18 8" />
</svg>

**Comment by XengShi** [comment]
> > > Okay for now let me try to make the google apps thingy and what about the tooltip thing? Could you manage to add it on the location? #96
> > 
> > I haven't tried again
> 
> Can anyone code me this 9 dots icon thingy as svg code please :)

Just figma it man

**Comment by itz-rj-here** [comment]
> > > > Okay for now let me try to make the google apps thingy and what about the tooltip thing? Could you manage to add it on the location? #96
> > > 
> > > 
> > > I haven't tried again
> > 
> > 
> > Can anyone code me this 9 dots icon thingy as svg code please :)
> 
> Just figma it man

Im Noob 😂

**Comment by XengShi** [comment]
![menu-grid](https://github.com/user-attachments/assets/1a00a3b3-97bd-47c0-9e9d-209f887a10ff)

@itz-rj-here 

`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
<path d="M8 6C8 6.53043 7.78929 7.03914 7.41421 7.41421C7.03914 7.78929 6.53043 8 6 8C5.46957 8 4.96086 7.78929 4.58579 7.41421C4.21071 7.03914 4 6.53043 4 6C4 5.46957 4.21071 4.96086 4.58579 4.58579C4.96086 4.21071 5.46957 4 6 4C6.53043 4 7.03914 4.21071 7.41421 4.58579C7.78929 4.96086 8 5.46957 8 6ZM8 12C8 12.5304 7.78929 13.0391 7.41421 13.4142C7.03914 13.7893 6.53043 14 6 14C5.46957 14 4.96086 13.7893 4.58579 13.4142C4.21071 13.0391 4 12.5304 4 12C4 11.4696 4.21071 10.9609 4.58579 10.5858C4.96086 10.2107 5.46957 10 6 10C6.53043 10 7.03914 10.2107 7.41421 10.5858C7.78929 10.9609 8 11.4696 8 12ZM6 20C6.53043 20 7.03914 19.7893 7.41421 19.4142C7.78929 19.0391 8 18.5304 8 18C8 17.4696 7.78929 16.9609 7.41421 16.5858C7.03914 16.2107 6.53043 16 6 16C5.46957 16 4.96086 16.2107 4.58579 16.5858C4.21071 16.9609 4 17.4696 4 18C4 18.5304 4.21071 19.0391 4.58579 19.4142C4.96086 19.7893 5.46957 20 6 20ZM14 6C14 6.53043 13.7893 7.03914 13.4142 7.41421C13.0391 7.78929 12.5304 8 12 8C11.4696 8 10.9609 7.78929 10.5858 7.41421C10.2107 7.03914 10 6.53043 10 6C10 5.46957 10.2107 4.96086 10.5858 4.58579C10.9609 4.21071 11.4696 4 12 4C12.5304 4 13.0391 4.21071 13.4142 4.58579C13.7893 4.96086 14 5.46957 14 6ZM12 14C12.5304 14 13.0391 13.7893 13.4142 13.4142C13.7893 13.0391 14 12.5304 14 12C14 11.4696 13.7893 10.9609 13.4142 10.5858C13.0391 10.2107 12.5304 10 12 10C11.4696 10 10.9609 10.2107 10.5858 10.5858C10.2107 10.9609 10 11.4696 10 12C10 12.5304 10.2107 13.0391 10.5858 13.4142C10.9609 13.7893 11.4696 14 12 14ZM14 18C14 18.5304 13.7893 19.0391 13.4142 19.4142C13.0391 19.7893 12.5304 20 12 20C11.4696 20 10.9609 19.7893 10.5858 19.4142C10.2107 19.0391 10 18.5304 10 18C10 17.4696 10.2107 16.9609 10.5858 16.5858C10.9609 16.2107 11.4696 16 12 16C12.5304 16 13.0391 16.2107 13.4142 16.5858C13.7893 16.9609 14 17.4696 14 18ZM18 8C18.5304 8 19.0391 7.78929 19.4142 7.41421C19.7893 7.03914 20 6.53043 20 6C20 5.46957 19.7893 4.96086 19.4142 4.58579C19.0391 4.21071 18.5304 4 18 4C17.4696 4 16.9609 4.21071 16.5858 4.58579C16.2107 4.96086 16 5.46957 16 6C16 6.53043 16.2107 7.03914 16.5858 7.41421C16.9609 7.78929 17.4696 8 18 8ZM20 12C20 12.5304 19.7893 13.0391 19.4142 13.4142C19.0391 13.7893 18.5304 14 18 14C17.4696 14 16.9609 13.7893 16.5858 13.4142C16.2107 13.0391 16 12.5304 16 12C16 11.4696 16.2107 10.9609 16.5858 10.5858C16.9609 10.2107 17.4696 10 18 10C18.5304 10 19.0391 10.2107 19.4142 10.5858C19.7893 10.9609 20 11.4696 20 12ZM18 20C18.5304 20 19.0391 19.7893 19.4142 19.4142C19.7893 19.0391 20 18.5304 20 18C20 17.4696 19.7893 16.9609 19.4142 16.5858C19.0391 16.2107 18.5304 16 18 16C17.4696 16 16.9609 16.2107 16.5858 16.5858C16.2107 16.9609 16 17.4696 16 18C16 18.5304 16.2107 19.0391 16.5858 19.4142C16.9609 19.7893 17.4696 20 18 20Z" fill="#707693"/>
</svg>`

**Comment by XengShi** [comment]
> @itz-rj-here https://icon-sets.iconify.design/ Check here
> 
> https://icon-sets.iconify.design/material-symbols/apps/ https://icon-sets.iconify.design/mdi/apps/
> 
> https://icon-sets.iconify.design/material-symbols/account-circle/ https://icon-sets.iconify.design/mdi/account-circle/

Thanks for this, I use  iconify extension on figma for getting icons, now I know I can simply visit the site for getting icons.

**Comment by itz-rj-here** [comment]
> > @itz-rj-here https://icon-sets.iconify.design/ Check here
> > https://icon-sets.iconify.design/material-symbols/apps/ https://icon-sets.iconify.design/mdi/apps/
> > https://icon-sets.iconify.design/material-symbols/account-circle/ https://icon-sets.iconify.design/mdi/account-circle/
> 
> Thanks for this, I use iconify extension on figma for getting icons, now I know I can simply visit the site for getting icons.

Great.
