### ISSUE TITLE
[Feature request] - Custom location for weather

### ISSUE THREAD

**Issue by MattiaPARRINELLO** [XengShi/materialYouNewTab#164]
Hello, it would be cool to have an option to use a custom location for the weather. For example, my computer have a weird problem with localization and locate me 40km away, that's why a custom location could be a useful feature.

**Comment by itz-rj-here** [comment]
Hello @MattiaPARRINELLO, 
The feature you are requesting for is already included to the extention. 
Click on the menu section by clicking on the bottom right corner circle button, then scroll down and you will find an option to enter your weather location. On there you will be able to set your location easily.

**Comment by prem-k-r** [comment]
![image](https://github.com/user-attachments/assets/67010199-975b-432b-8a57-c3304487aac4)
@MattiaPARRINELLO please make sure that you are using latest version

**Comment by prem-k-r** [comment]
> ![image](https://private-user-images.githubusercontent.com/60751338/384278476-67010199-975b-432b-8a57-c3304487aac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjUyMTUsIm5iZiI6MTczMTA2NDkxNSwicGF0aCI6Ii82MDc1MTMzOC8zODQyNzg0NzYtNjcwMTAxOTktOTc1Yi00MzJiLThhNTctYzMzMDQ0ODdhYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZjgxOGI5YjgwZjQ0ODdkYTFhMjY3MGE1OGViMzIxM2I1M2ZjZGM2N2RjYThiOWQwZjhhYTc5MGUxYjBhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LktJo_Vg85Qu_KW4snVY1ZqCNTUWC9Ni91M42qJV-_M) @MattiaPARRINELLO please make sure that you are using latest version

you can download the ZIP file by clicking on the Code button. On the repository page, look for a green button labeled **Code**. Click on the **Code** button, and in the dropdown menu, select **Download ZIP**.

**Comment by itz-rj-here** [comment]
@XengShi You can close this pr as completed.

**Comment by itz-rj-here** [comment]
As the feature already included.
