### ISSUE TITLE
Voice searching doesn't work in Brave

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#176]
> > > > Hmm, the feature doesn't work for me. I click on the microphone icon, which shows "Listening..." for a few seconds and goes back to "Type here..." afterward. It required browser (Brave) permission, so I accepted it. It doesn't work anyway.
> > >
> > > icon was visible in Brave? included changes from this PR?
> >
> > What icon? I'm on `main`'s latest commit, so yeah. I see Brave's icon signalizing that the webpage is listening for my input, but it's just for a few seconds, nothing more. The microphone icon in the UI of this extension is visible, of course.
> 
> ah sorry, I meant Mic icon. Are you using any other custom user agent? can you please share your user agent ![image](https://private-user-images.githubusercontent.com/60751338/385008183-98db771f-8cd0-4890-89d3-beb16a0584af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDc3NTcsIm5iZiI6MTczMTM0NzQ1NywicGF0aCI6Ii82MDc1MTMzOC8zODUwMDgxODMtOThkYjc3MWYtOGNkMC00ODkwLTg5ZDMtYmViMTZhMDU4NGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE3NTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2NkZmY1MTY5YzZiOGI3MGMwNmMxMzg4YTk2MzE5ZjMzMmNhN2ZmZDkyN2U4ZWQxYmUxNjk5ZGQxYjVjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e7B8-DyTFNNRIWaWlZGL_6acuBopmyh35O2Vle97AQg)

Here it's:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
```

_Originally posted by @ceskyDJ in https://github.com/XengShi/materialYouNewTab/issues/175#issuecomment-2468730903_

**Comment by ceskyDJ** [comment]
@prem-k-r, could we please bring the discussion here? We need to finish the string in the PR's chat.

**Comment by prem-k-r** [comment]
> > > > > Hmm, the feature doesn't work for me. I click on the microphone icon, which shows "Listening..." for a few seconds and goes back to "Type here..." afterward. It required browser (Brave) permission, so I accepted it. It doesn't work anyway.
> > > > 
> > > > 
> > > > icon was visible in Brave? included changes from this PR?
> > > 
> > > 
> > > What icon? I'm on `main`'s latest commit, so yeah. I see Brave's icon signalizing that the webpage is listening for my input, but it's just for a few seconds, nothing more. The microphone icon in the UI of this extension is visible, of course.
> > 
> > 
> > ah sorry, I meant Mic icon. Are you using any other custom user agent? can you please share your user agent ![image](https://private-user-images.githubusercontent.com/60751338/385008183-98db771f-8cd0-4890-89d3-beb16a0584af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDc3NTcsIm5iZiI6MTczMTM0NzQ1NywicGF0aCI6Ii82MDc1MTMzOC8zODUwMDgxODMtOThkYjc3MWYtOGNkMC00ODkwLTg5ZDMtYmViMTZhMDU4NGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE3NTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2NkZmY1MTY5YzZiOGI3MGMwNmMxMzg4YTk2MzE5ZjMzMmNhN2ZmZDkyN2U4ZWQxYmUxNjk5ZGQxYjVjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e7B8-DyTFNNRIWaWlZGL_6acuBopmyh35O2Vle97AQg)
> 
> Here it's:
> 
> ```
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
> ```
> 
> _Originally posted by @ceskyDJ in [#175 (comment)](https://github.com/XengShi/materialYouNewTab/pull/175#issuecomment-2468730903)_

Ok

**Comment by ceskyDJ** [comment]
I see. I know about whisper-web (https://github.com/xenova/whisper-web), which could replace the Google API for STT (used internally by Web Speech API in Chromium browsers), but you'd need a way how to stream voice to it.

However, I found https://github.com/ccoreilly/vosk-browser. It could solve the problem entirely, but I wonder if it works and how good it is. (Maybe there are other simple solutions, but I only had a little time to Google it.)

**Comment by prem-k-r** [comment]
Hided mic icon for brave.

**Comment by XengShi** [comment]
> Hided mic icon for brave.
> 

![IMG_20241114_121850.jpg](https://github.com/user-attachments/assets/d35a5322-69a2-49e7-81b5-841c40e72d6f)


How about adding option like this

**Comment by prem-k-r** [comment]
> I see. I know about whisper-web ([xenova/whisper-web](https://github.com/xenova/whisper-web)), which could replace the Google API for STT (used internally by Web Speech API in Chromium browsers), but you'd need a way how to stream voice to it.
> 
> However, I found [ccoreilly/vosk-browser](https://github.com/ccoreilly/vosk-browser). It could solve the problem entirely, but I wonder if it works and how good it is. (Maybe there are other simple solutions, but I only had a little time to Google it.)

A bit complex. I can't do.
Vosk-Browser supports only 13 languages. Yeah others better option may be available.

For Chrome and Edge, it’s best to keep using the Web Speech API, 
and for Firefox, Brave, Opera, and Safari, someone can use a third-party library.

**Comment by prem-k-r** [comment]
> > Hided mic icon for brave.
> 
> ![IMG_20241114_121850.jpg](https://private-user-images.githubusercontent.com/48722764/386076006-d35a5322-69a2-49e7-81b5-841c40e72d6f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzQ2MTIsIm5iZiI6MTczMTU3NDMxMiwicGF0aCI6Ii80ODcyMjc2NC8zODYwNzYwMDYtZDM1YTUzMjItNjlhMi00OWU3LTgxYjUtODQxYzQwZTcyZDZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNTQ1YmViODk5Y2MwNDJkN2RlYzI5ODE0MTFjODllMWYxZWU3ZTNlNGQzMzEwNjhlYzAxMDRkM2NhOGEzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zgqNbVHswfbi1zFXvpycL_G-J92-EyZSkauEHtNMxc4)
> 
> How about adding option like this

on it

**Comment by ceskyDJ** [comment]
> > I see. I know about whisper-web ([xenova/whisper-web](https://github.com/xenova/whisper-web)), which could replace the Google API for STT (used internally by Web Speech API in Chromium browsers), but you'd need a way how to stream voice to it.
> > 
> > However, I found [ccoreilly/vosk-browser](https://github.com/ccoreilly/vosk-browser). It could solve the problem entirely, but I wonder if it works and how good it is. (Maybe there are other simple solutions, but I only had a little time to Google it.)
> 
> A bit complex. I can't do.
> Vosk-Browser supports only 13 languages. Yeah others better option may be available.
> 
> For Chrome and Edge, it’s best to keep using the Web Speech API, 
> and for Firefox, Brave, Opera, and Safari, someone can use a third-party library.

I'd look at it, but I don't have enough free time as it probably will take a lot. Let this issue open, and we'll see how the situation will change. I think as this is an open-source project, we should at least give users the ability to use some privacy-friendly locally hosted solution or provide them with a way to use anything they want to.
