### ISSUE TITLE
Need fix: Searchbar Text Input area is fixed

### ISSUE THREAD

**Issue by prem-k-r** [XengShi/materialYouNewTab#181]
- [x] `searchQ` div width is fix right now wrt English text.
![image](https://github.com/user-attachments/assets/1fbf5cc5-75f2-42e0-8e93-6290cc0df5d6) 
It need to be dynamically adaptive wrt `searchControls` div. This results in unwanted behaviour for other languages:
![image](https://github.com/user-attachments/assets/3ec0ae23-ef0a-4136-ac84-8290f6a01627)
![image](https://github.com/user-attachments/assets/6ce353f7-402f-492d-ab86-47d0919619e2)

- [x] Cursor type changed to Text on Search Icon too, it shouldn't.

**Comment by itz-rj-here** [comment]
You can change the "অনুসন্ধান করুন" to "খুজুন" If needed. It's kind of similar to search but "খুজুন" means look for thats the issue.

**Comment by itz-rj-here** [comment]
> > You can change the "অনুসন্ধান করুন" to "খুজুন" If needed. It's kind of similar to search but "খুজুন" means look for thats the issue.
> 
> This won't be solving the issue, other languages have lengthier text too. Just needs a quick CSS fix. I'm not good at css

I think we have a guy
can't remember correctly maybe Minuga

**Comment by XengShi** [comment]
> > You can change the "অনুসন্ধান করুন" to "খুজুন" If needed. It's kind of similar to search but "খুজুন" means look for thats the issue.
> 
> This won't be solving the issue, other languages have lengthier text too. 
> Just needs a quick CSS fix. I'm not good at css
> 


Just set the max width for text area or add ::after and place it behind mic 🎤 button give it the same background as searchbar.
