### ISSUE TITLE
Make it more responsive

### ISSUE THREAD

**Issue by Shriram2005** [XengShi/materialYouNewTab#182]
its settings section is not responsive in my laptop screen , all texts are overlapping each other i have 14.6 inch laptop screen. is it just me or everyone?

![image](https://github.com/user-attachments/assets/61a7d867-7b34-4edd-ba3f-30dd388514f8)

**Comment by itz-rj-here** [comment]
What is your zoom size?

**Comment by Shriram2005** [comment]
> What is your zoom size?

its default 100% size. Maybe my laptop issue, but you may check in others laptops for conformation!

**Comment by XengShi** [comment]
> > What is your zoom size?
> 
> its default 100% size. Maybe my laptop issue, but you may check in others laptops for conformation!

Yes, it looks different on different devices due to varying screen sizes. You can adjust it by simply zooming in or out on the page.

**Comment by prem-k-r** [comment]
I don't think this has anything to do with zooming, but rather with the font size. It's probably set to Large.
You can fix it by going to `Settings > Appearance > Font Size > Medium`.
