### ISSUE TITLE
Add ability to select items from search autocomplete via keyboard

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#183]
Now, when I want to select some autocomplete item, I need to click on it with a mouse. I want to have an option to stay on my keyboard, so the whole process is:

1. Search input is focused on the page load (e.g., `element.focus()`).
2. When I type something, autocomplete reveals.
3. I can use the Bottom and Top arrow keys to select a completed search query.
4. I press the Enter key, and it starts searching the selected query via the selected search engine (e.g., Google).

**Comment by itz-rj-here** [comment]
Doesn’t it work? I thought it might work bruh.

**Comment by ceskyDJ** [comment]
Huh, it works for you? I should be on the latest commit of `main`, and it doesn't work. The input isn't autofocus, and I can't select an item from autocomplete via the Top and Bottom arrow keys on my keyboard.

**Comment by prem-k-r** [comment]
> Doesn’t it work? I thought it might work bruh.

nope

**Comment by itz-rj-here** [comment]
> > Doesn’t it work? I thought it might work bruh.
> 
> nope

Didn't noticed it cause i usually don't use it as all shortcuts are included on the new tab extention :)

**Comment by itz-rj-here** [comment]
@Minuga-RC

**Comment by Minuga-RC** [comment]
Ik I could easily do all of those but I'm toooooooo lazy af

**Comment by itz-rj-here** [comment]
> Ik I could easily do all of those but I'm toooooooo lazy af

Get some protein. -_-

**Comment by Minuga-RC** [comment]
I need those ADHD drugs

**Comment by itz-rj-here** [comment]
> I need those ADHD drugs

0.0

**Comment by itz-rj-here** [comment]
@prem-k-r do you have minimum brain to fix this?

**Comment by itz-rj-here** [comment]
@XengShi I think I found a solution. I want you to give me some time to check this until don't release any update please :)

**Comment by itz-rj-here** [comment]
@prem-k-r I need a help. Imagine, I want to use a "background-color: var(--accentLightTint-blue);" on javascript. How i can use it?

**Comment by prem-k-r** [comment]
> @prem-k-r I need a help. Imagine, I want to use a "background-color: var(--accentLightTint-blue);" on javascript. How i can use it?

one way is to create `style` within js, just as in dark theme.

other can be like below
const resultSelect = document.getElementById("resultItem");
resultSelect.style.background-color = #fff;

**Comment by ceskyDJ** [comment]
> 1. Search input is focused on the page load (e.g., `element.focus()`).

@prem-k-r, you forgot about this part in #202.

**Comment by ceskyDJ** [comment]
> > > 1. Search input is focused on the page load (e.g., `element.focus()`).
> > 
> > 
> > @prem-k-r, you forgot about this part in #202.
> 
> ah right, I'll check

It'd be great! If you add it, I can start writing just after the page loads.

**Comment by prem-k-r** [comment]
> > > > 1. Search input is focused on the page load (e.g., `element.focus()`).
> > > 
> > > 
> > > @prem-k-r, you forgot about this part in #202.
> > 
> > 
> > ah right, I'll check
> 
> It'd be great! If you add it, I can start writing just after the page loads.

Not working, browser's own searchbar overrides it.
can someone else look into it?

**Comment by itz-rj-here** [comment]
> > > > > 1. Search input is focused on the page load (e.g., `element.focus()`).
> > > > 
> > > > 
> > > > @prem-k-r, you forgot about this part in #202.
> > > 
> > > 
> > > ah right, I'll check
> > 
> > It'd be great! If you add it, I can start writing just after the page loads.
> 
> Not working, browser's own searchbar overrides it.
> can someone else look into it?

What does that mean either? I didn’t even understand 🗿

**Comment by prem-k-r** [comment]
> > > > > > 1. Search input is focused on the page load (e.g., `element.focus()`).

> > > It'd be great! If you add it, I can start writing just after the page loads.

> > Not working, browser's own searchbar overrides it.
> > can someone else look into it?
> 
> What does that mean either? I didn’t even understand 🗿

When we open the browser or a new tab, we can't start typing a query in the search bar on our homepage right away. First, we have to click the search bar with the mouse before we can start typing.

Current behavior: It starts with the browser's own search bar at the top of the page.
What is needed: The focus should start on our homepage search bar.
I am unable to implement this, could do only such that clicking anywhere on the homepage will put the focus on our homepage search bar

**Comment by itz-rj-here** [comment]
> > > > > > > 1. Search input is focused on the page load (e.g., `element.focus()`).
> 
> > > > It'd be great! If you add it, I can start writing just after the page loads.
> 
> > > Not working, browser's own searchbar overrides it.
> > > can someone else look into it?
> > 
> > 
> > What does that mean either? I didn’t even understand 🗿
> 
> When we open the browser or a new tab, we can't start typing a query in the search bar on our homepage right away. First, we have to click the search bar with the mouse before we can start typing.
> 
> Current behavior: It starts with the browser's own search bar at the top of the page. What is needed: The focus should start on our homepage search bar. I am unable to implement this, could do only such that clicking anywhere on the homepage will put the focus on our homepage search bar

I don't think it's actually possible. Cause if we click on the + icon on the top when the new tab opens it automatically goes to the browsers own search bar. Still let me check if i find something.
