### ISSUE TITLE
Transliteration for search engines 

### ISSUE THREAD

**Issue by XengShi** [XengShi/materialYouNewTab#190]
![Screenshot from 2024-11-18 11-14-33](https://github.com/user-attachments/assets/2106312c-86a0-42ce-a927-cd289fb06483)
![Screenshot from 2024-11-18 11-10-24](https://github.com/user-attachments/assets/25895053-052a-4a45-91f2-8f934b229290)

How about implementing transliteration for search engines in the selected language?

@itz-rj-here , @prem-k-r  Could you please also coordinate with the language translator to include translations for the search engines as well?

**Comment by prem-k-r** [comment]
Ok, will do

**Comment by itz-rj-here** [comment]
> ![Screenshot from 2024-11-18 11-14-33](https://private-user-images.githubusercontent.com/48722764/387080656-2106312c-86a0-42ce-a927-cd289fb06483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTIwODAsIm5iZiI6MTczMTkxMTc4MCwicGF0aCI6Ii80ODcyMjc2NC8zODcwODA2NTYtMjEwNjMxMmMtODZhMC00MmNlLWE5MjctY2QyODlmYjA2NDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA2MzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjExM2M1MTg5MWQ4NDY0NjM5M2MwZDZjOWE3MGQ2ZmZiMWI4M2NiNTg3MmM3OTNiNjE4ZGMwZjIyZjVmMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q4BXfncIXEXOKglXwnR5zJGOU3njwN9TsZnLYAYp1jM) ![Screenshot from 2024-11-18 11-10-24](https://private-user-images.githubusercontent.com/48722764/387080679-25895053-052a-4a45-91f2-8f934b229290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTIwODAsIm5iZiI6MTczMTkxMTc4MCwicGF0aCI6Ii80ODcyMjc2NC8zODcwODA2NzktMjU4OTUwNTMtMDUyYS00YTQ1LTkxZjItOGY5MzRiMjI5MjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA2MzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MGU1YzVkODc4ZTZhOWYxODdlODdkYjI5MjUyODgyN2MwODNlNzhkZDliYTc2NGY4MzY2MDc1YmRhYmM2NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.unaAKXnvFx1BKjjBa5Z9UaC16GgmCdq_XcNSCxEPuYc)
> 
> How about implementing transliteration for search engines in the selected language?
> 
> @itz-rj-here , @prem-k-r Could you please also coordinate with the language translator to include translations for the search engines as well?

Agreed.

**Comment by prem-k-r** [comment]
@XengShi should we transliterate all google apps too?

**Comment by XengShi** [comment]
> @XengShi should we transliterate all google apps too? 

I don't think...

**Comment by prem-k-r** [comment]
Okay

**Comment by ceskyDJ** [comment]
> @XengShi should we transliterate all google apps too?

It could be good as at least in Czechia these names are localized.

**Comment by prem-k-r** [comment]
> > @XengShi should we transliterate all google apps too?
> 
> It could be good as at least in Czechia these names are localized.

there are 33 apps there lol
