### ISSUE TITLE
Please release the next version version 2.4

### ISSUE THREAD

**Issue by fisforfaheem** [XengShi/materialYouNewTab#199]
its been whole 3 weeks now PLEASe

**Comment by itz-rj-here** [comment]
You seem like a pretty knowledgeable person based on your profile. However, you don't even appear to be 6+ based on your actions here.
We have our own personal life to lead, as I have previously stated. You should thus be patient till the new version is released while we finish our coding and other tasks.
The 2.3 version doesn't even seem problematic to me. Where is the issue, then?
There isn't a significant upgrade or anything in the next release. Only a few minor bug fixes and some new language.

Everyone should be patient for wonderful things, as we all know.

**Comment by fisforfaheem** [comment]
Ah, thank you for your thoughtful assessment of my perceived age and patience levels—truly a masterclass in respectful communication, as GitHub encourages. I appreciate your perspective on the updates and how they "don't seem problematic" to you. Clearly, my concerns must be invalid if they don’t align with your experience, right?

I’ll take your advice to heart and eagerly await these "minor bug fixes" and "new language." After all, patience is a virtue... though I suspect it might also be a coping mechanism for managing this enlightening conversation.

Looking forward to more pearls of wisdom from you. Cheers!

**Comment by itz-rj-here** [comment]
"Thanks for your enthusiasm! As mentioned, the update includes minor fixes and isn’t a major release. We’re balancing this with other responsibilities, so we appreciate your patience while we finalize it. Stay tuned!

**Comment by prem-k-r** [comment]
@fisforfaheem 
https://github.com/XengShi/materialYouNewTab/releases/tag/v2.4
