### ISSUE TITLE
Feature Request - Adding YT Music on shortcuts

### ISSUE THREAD

**Issue by itz-rj-here** [XengShi/materialYouNewTab#207]
![image](https://github.com/user-attachments/assets/d2a763c1-3c51-48a9-985a-03a735073547)

Why don't we add it on the Google Apps icon. Instead of Google search engine shortcut on the Google Apps?

**Comment by itz-rj-here** [comment]
#205

**Comment by prem-k-r** [comment]
Can place it in google apps, by removing out Gemini. 

He was asking to add in shortcuts.. we may add some more custom svg, those will not be in shortcuts by default but when a new shortcut of that domain created then fetch icon from that svg.

**Comment by itz-rj-here** [comment]
I also want facebook to add on shortcuts if XengShi Agrees

**Comment by itz-rj-here** [comment]
@prem-k-r Remove the gmail as it already here

![image](https://github.com/user-attachments/assets/4c0ff952-4b31-458d-a93d-c6a975e60eee)

**Comment by XengShi** [comment]
> I also want facebook to add on shortcuts if XengShi Agrees

I disagree, instead you are free to remove the Instagram shortcuts 🙃

**Comment by XengShi** [comment]
> ![image](https://github.com/user-attachments/assets/d2a763c1-3c51-48a9-985a-03a735073547)
> 
> Why don't we add it on the Google Apps icon. Instead of Google search engine shortcut on the Google Apps?

Removing the Google shortcut isn't ideal, as our extension has no direct link to www.google.com.

**Comment by itz-rj-here** [comment]
> > I also want facebook to add on shortcuts if XengShi Agrees
> 
> I disagree, instead you are free to remove the Instagram shortcuts 🙃

Fine :)

**Comment by itz-rj-here** [comment]
> > I also want facebook to add on shortcuts if XengShi Agrees
> 
> I disagree, instead you are free to remove the Instagram shortcuts 🙃

I use fb and insta :)

**Comment by XengShi** [comment]
> > > I also want facebook to add on shortcuts if XengShi Agrees
> > 
> > I disagree, instead you are free to remove the Instagram shortcuts 🙃
> 
> I use fb and insta :)

Those apps are designed to waste the user's time, they just want you to keep scrolling all the day 😆

**Comment by itz-rj-here** [comment]
> > > > I also want facebook to add on shortcuts if XengShi Agrees
> > > 
> > > 
> > > I disagree, instead you are free to remove the Instagram shortcuts 🙃
> > 
> > 
> > I use fb and insta :)
> 
> Those apps are designed to waste the user's time, they just want you to keep scrolling all the day 😆

I wouldn't have used it. But my crush deactivated her id for no reason now i had to open fb to text her :)
