### ISSUE TITLE
Background Image is needed

### ISSUE THREAD

**Issue by AK-Programs** [XengShi/materialYouNewTab#210]
I want my background image because only blue color i don't like.

**Comment by XengShi** [comment]
@itz-rj-here

**Comment by itz-rj-here** [comment]
> I want my background image because only blue color i don't like.

Hmm Okay. We will try to add this feature soon.

**Comment by itz-rj-here** [comment]
@AK-Programs Hey there, For your feature request we might need more time to add that feature.

For now, use other themes on the menu section until we add the image adding feature. :)
Have fun.

**Comment by itz-rj-here** [comment]
@prem-k-r Check if you could make it. Before a new release launched. If not we will do this some days later.

**Comment by itz-rj-here** [comment]
#30 pr was added as adding image support but not merged cause of the conflicts issue and user wasn't active.

**Comment by prem-k-r** [comment]
> @prem-k-r Check if you could make it. Before a new release launched. If not we will do this some days later.

I can check later

**Comment by prem-k-r** [comment]
> #30 pr was added as adding image support but not merged cause of the conflicts issue and user wasn't active.

That's was bit different, custom image upload-choose was not there.

**Comment by itz-rj-here** [comment]
> > #30 pr was added as adding image support but not merged cause of the conflicts issue and user wasn't active.
> 
> That's was bit different, custom image upload-choose was not there.

You are right with that.

**Comment by prem-k-r** [comment]
Ah forgot, there was an open issue on this.. 
Please manually close it. Thanks
