### ISSUE TITLE
It aint working on fedora

### ISSUE THREAD

**Issue by Juoelenis** [XengShi/materialYouNewTab#22]
I tried running it on fedora, idk is it just me or is it not working, i tried it in a vm and physical machine, the same issue

**Comment by ewingwm** [comment]
What web browser are you using?

**Comment by XengShi** [comment]
If you are using Fedora, it’s likely that Firefox is your default browser. To [Download](https://addons.mozilla.org/en-GB/firefox/addon/material-you-newtab) the extension for Firefox, visit the Mozilla Add-ons store
