### ISSUE TITLE
Customization FAB is not centered 

### ISSUE THREAD

**Issue by HeCodesInGithub** [XengShi/materialYouNewTab#223]
![image](https://github.com/user-attachments/assets/3598edd8-cbb5-4043-b51c-0356ae14b0a0)

The Customization FAB is not centered according in 90% view zoom. 
It is not centered until 125% view zoom.

**Comment by itz-rj-here** [comment]
Hello there, can you please describe some of the information to us. So that, we can understand properly in which kind of device the problem you are facing.

**Comment by Thunder-Blaze** [comment]
I think he is referring to the settings/menu button (Customization Floating Action Button - the defination I found on Google) which got fixed in #324

**Comment by prem-k-r** [comment]
@XengShi please close this as completed as it is fixed.
