### ISSUE TITLE
Adding a Background Picture

### ISSUE THREAD

**Issue by DiptangshuRoy** [XengShi/materialYouNewTab#253]
It will be impressive if you add an option to toggle fetching an aesthetic random Background Picture every day or in some hours.

**Comment by itz-rj-here** [comment]
It's already added to the current development code. Thanks for the suggestion. Now you can close the issue. #240

**Comment by prem-k-r** [comment]
> It will be impressive if you add an option to toggle fetching an aesthetic random Background Picture every day or in some hours.

we will consider it.
free and high-traffic.. Lorem Picsum seems good option
