### ISSUE TITLE
Add To Do List

### ISSUE THREAD

**Issue by rajvikash18113** [XengShi/materialYouNewTab#255]
Extension is preety Good, but if you add 1 more option that is to add anyone can add their To Do List and mark as done or not done. And To Do list should reset daily after 23:59.

**Comment by rajvikash18113** [comment]
but still there is no option in the extension to add to do list

**Comment by rajvikash18113** [comment]
![New-Tab](https://github.com/user-attachments/assets/1a87992d-bd4d-4007-81d9-b81d4549fafa)
why to do list option is not in my device till now. i have also installed it again

**Comment by prem-k-r** [comment]
@rajvikash18113 download from here and manually install
https://github.com/XengShi/materialYouNewTab/archive/refs/heads/main.zip

or else wait for a week to install from chrome web store

**Comment by rajvikash18113** [comment]
The To-Do List feature is working, but there is an issue where **the list gets deleted or reset at 23:59 each day,** requiring us to recreate it daily.

Instead, it would be better if the list remains persistent every day. At 23:59, only the status of all tasks should reset to "undone" or "unchecked," allowing us to mark them as completed again the next day. This way, we won't lose our tasks and can easily manage recurring activities.

**Comment by prem-k-r** [comment]
After #337, you can pin an item. 

@Thunder-Blaze can you please add a scenario.. if pinned item is marked as completed, next day, reset it's status to pending.

**Comment by prem-k-r** [comment]
Umm, maybe we should not delete pending task too.. 

Next day: 
if pin and complete -> reset status to pending 
Delete completed
Leave pending as it is.. no auto deletion 


Thoughts? What should we go with

**Comment by Thunder-Blaze** [comment]
Hmm, seems like good idea to me, should I add this functionality to #337 or wait for it to get merged ?

**Comment by prem-k-r** [comment]
Maybe in 337

**Comment by Thunder-Blaze** [comment]
Got it 👍🏻

**Comment by prem-k-r** [comment]
Hi @rajvikash18113, done! It's added by Thunder-Blaze. You can pin the tasks to ensure they won't get deleted the next day. Additionally, any pinned and checked tasks will automatically reset to an unchecked status at 23:59.
You can download it from the link provided above right now, or you can wait 2-3 days for it to become available on the Chrome Web Store.

**Comment by rajvikash18113** [comment]
okay, Thankyou So Much❤️
