### ISSUE TITLE
Add the Options to add the shortcut icon's from the client side to improve customization

### ISSUE THREAD

**Issue by Athrudev** [XengShi/materialYouNewTab#259]

**Comment by TrucuLenGhost55** [comment]
Yes, this and the normal bookmarks tab would make it just perfect.

**Comment by prem-k-r** [comment]
Unfortunately, Chrome and other browsers doesn't allow any extension to control the visibility of the bookmarks bar specifically on a custom new tab.
You can Press `Ctrl + Shift + B` to show the bookmarks bar but this will be visible on all tabs.
Even if in the future we introduce bookmarks, it will be a custom one. Moreover this extension will need bookmark permission.
