### ISSUE TITLE
Bookmarks missing after using in Google Chrome

### ISSUE THREAD

**Issue by WhitePoodleMoth** [XengShi/materialYouNewTab#27]
I noticed that after using the extension in Google Chrome, the starred (favorites) icon in the top corner disappears.

**Comment by WhitePoodleMoth** [comment]
Could you please add the bug label to this issue?

**Comment by saiteja-yadav** [comment]
Please add a video...

**Comment by saiteja-yadav** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Starred Icon Example</title>
    <style>
        .starred-icon {
            font-size: 24px;
            color: gold;
            position: fixed;
            top: 10px;
            right: 10px;
        }
    </style>
</head>
<body>
    <header>
        
        <div class="starred-icon" id="favIcon">
            &#9733; 
        </div>
    </header>

    <main>
        <h1>Welcome to the Starred Icon Page</h1>
        <p>This is a sample page to demonstrate the position of a starred icon in the top corner.</p>
    </main>

    <script>
        // Optional: Functionality to handle extension interference or to check if the icon is hidden
        document.addEventListener('DOMContentLoaded', function() {
            const favIcon = document.getElementById('favIcon');
            if (favIcon) {
                favIcon.style.display = 'block'; // Ensure the icon is visible
            }
        });
    </script>
</body>
</html>
#27 issue

**Comment by WhitePoodleMoth** [comment]
this issue is with the bookmark of the Google Chrome

**Comment by Asifali2o** [comment]
If your bookmarks are missing in Google Chrome, try these steps:

Show Bookmarks Bar: Press Ctrl + Shift + B (Windows) or Cmd + Shift + B (Mac).

Bookmarks Manager: Click the three dots > Bookmarks > Bookmark Manager.

Restore Backup:

Close Chrome.
Go to:
Windows: C:\Users\[Your Username]\AppData\Local\Google\Chrome\User Data\Default
Mac: ~/Library/Application Support/Google/Chrome/Default
Rename Bookmarks to Bookmarks.old and Bookmarks.bak to Bookmarks.
Reopen Chrome.
Sign In: Ensure you’re logged into your Google account.

Reset Settings: Go to Settings > Advanced > Reset and clean up.

Reinstall Chrome: Uninstall and reinstall as a last resort.
You can visit kindly visit this [post](https://www.foxiina.com/).
