### ISSUE TITLE
Facing this error since 3 days 

### ISSUE THREAD

**Issue by sarfrazkhan48382** [XengShi/materialYouNewTab#281]
![image](https://github.com/user-attachments/assets/e2955b2e-350b-4175-a31a-2eadf2feb86a)
Any solution?

**Comment by prem-k-r** [comment]
enter your own WeatherAPI key
https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html

**Comment by sarfrazkhan48382** [comment]
> enter your own WeatherAPI key https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html

Thankssssss brotherrr 👍
