### ISSUE TITLE
Location, temperature & humidity is not updated 

### ISSUE THREAD

**Issue by M0hanrajp** [XengShi/materialYouNewTab#282]
### Issue:
entered "q=Bengaluru". for the input in `Enter your location` based on documentation input options 
format for entering the city name to be `city name e.g.: q=Paris`, home page does not update but
live test url updates within 1 sec.

The home page does not update with Location, temperature & humidity. 
![image](https://github.com/user-attachments/assets/19c58885-bcf1-455e-8bdd-68252bf8fe30)

but the same issue is not observed over https://xengshi.github.io/materialYouNewTab/
![image](https://github.com/user-attachments/assets/a36d965b-6596-480c-9e2b-14cdc7f1f252)

Could you please help to look into this ? 

Best Regards.

**Comment by prem-k-r** [comment]
you needed to enter just `Bengaluru`

problem is with weatherAPI api limit
enter your own WeatherAPI key
[xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)

**Comment by M0hanrajp** [comment]
> you needed to enter just `Bengaluru`
> 
> problem is with weatherAPI api limit enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)

Even entering just `Bengaluru` does not work, is getting weatherAPI key the only way ?

**Comment by XengShi** [comment]
> > you needed to enter just `Bengaluru`
> > 
> > problem is with weatherAPI api limit enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
> 
> Even entering just `Bengaluru` does not work, is getting weatherAPI key the only way ?

Bro, why you are entering just `Bengaluru` try
"Bangalore" once

**Comment by prem-k-r** [comment]
> > you needed to enter just `Bengaluru`
> > problem is with weatherAPI api limit enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
> 
> Even entering just `Bengaluru` does not work, is getting weatherAPI key the only way ?

Yes, 
Or just wait for next version, more shared API keys have been added.. but once it reaches limit next month, you will be back to this . 
Just get your own key na.. 2-3 minutes work and be done for forever

**Comment by M0hanrajp** [comment]
Ok thanks for your response.

**Comment by M0hanrajp** [comment]
> > > you needed to enter just `Bengaluru`
> > > 
> > > problem is with weatherAPI api limit enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
> > 
> > Even entering just `Bengaluru` does not work, is getting weatherAPI key the only way ?
> 
> Bro, why you are entering just `Bengaluru` try
> "Bangalore" once 

That also doesn't work 😂
