### ISSUE TITLE
Does the backup and restore include all the saved shortcuts ?

### ISSUE THREAD

**Issue by SmeetPatil** [XengShi/materialYouNewTab#286]
I use the shortcuts almost 99% of times when I open a new tab, and I have a lot of them so I just wanted to ask if they get backed up. If not then can you show me where they are stored in the 'localStorage' ??

**Comment by prem-k-r** [comment]
Backup:  everything including shortcuts and wallpaper 
Restore: everything 
Clear: delete custom/random wallpaper 
Reset: reset everything except wallpaper

**Comment by SmeetPatil** [comment]
Alright, thanks a lot!!
