### ISSUE TITLE
Is it possible to add facebook to shortcuts 

### ISSUE THREAD

**Issue by youtubetom** [XengShi/materialYouNewTab#295]
It is possible to add Facebook to shortcuts

**Comment by XengShi** [comment]
![IMG_20241209_110036.jpg](https://github.com/user-attachments/assets/c0bd1cd7-ad21-4f03-8379-58354056e0d9)

![IMG_20241209_110102.jpg](https://github.com/user-attachments/assets/8e6e9afc-584d-4b55-89d2-11b8e5a3e9e4)

!!!

**Comment by shubham29pathak** [comment]
just go to edit shortcut and click +

add whatever shortcut you want up to 10

**Comment by prem-k-r** [comment]
> just go to edit shortcut and click +
> 
> add whatever shortcut you want up to 10

50 is the limit  :)
