### ISSUE TITLE
[Feature] Add option to align shortcuts and aspect ratio while upload the wallpaper

### ISSUE THREAD

**Issue by notRyuk** [XengShi/materialYouNewTab#305]
Hey, 

I have been using this project using my default browser for quite a few time and I am used to align my bookmarks/shortcuts on the top (I generally turn off my bookmarks from the browser on the "new tab page").

So I would like the feature where the **shortcuts can be aligned based on the preference**.

And also I would prefer the **shortcut bubbles to be smaller than they** are as I notice they are in the default medium setting of the material you.

Also some of the issues I've noticed:
1. While uploading the wallpaper (90% of what i currently have are 3840x2160 and above aspect ratio) the extension asks me to specifically upload the wallpapers of 1920x1080 aspect ratio. I would like the extenstion to auto scale based on the aspect ratio.

**Comment by itz-rj-here** [comment]
@prem-k-r

**Comment by prem-k-r** [comment]
Hi, the extension doesn't specifically require wallpapers to be uploaded in 1920x1080 resolution; it is merely a warning. You can upload images of any dimension and aspect ratio. However, in some cases, the image might not be set as the background due to large image data.

**Comment by prem-k-r** [comment]
When setting those 3840x2160 images as wallpaper, are you not seeing them applied in the background?

**Comment by prem-k-r** [comment]
I have changed the codes.. storing images as Blobs instead of Base64.
Very large size images can also be set as wallpaper.
I'll draft it to PR later.

**Comment by notRyuk** [comment]
> When setting those 3840x2160 images as wallpaper, are you not seeing them applied in the background?

![image](https://github.com/user-attachments/assets/b84270c8-bd1b-421c-8678-274abd145917)
This is the exact thing that pops when im uploading images of higher dimensions.

**Comment by prem-k-r** [comment]
> > When setting those 3840x2160 images as wallpaper, are you not seeing them applied in the background?
> 
> ![image](https://private-user-images.githubusercontent.com/72451243/397585901-b84270c8-bd1b-421c-8678-274abd145917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzcyMDksIm5iZiI6MTczNDY3NjkwOSwicGF0aCI6Ii83MjQ1MTI0My8zOTc1ODU5MDEtYjg0MjcwYzgtYmQxYi00MjFjLTg2NzgtMjc0YWJkMTQ1OTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA2NDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZTU4NmYwZDkxOGZkZGQ3Y2EzYzE1OGM4YzJiZTNlMDllYjY2NWExOWViYmVlYjk5OWFkZTBlZjAwMDk0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yp7KMPzkxl2jpZP945dLz5XibSIQgeP_M4u_cRI7gZ4) This is the exact thing that pops when im uploading images of higher dimensions.

yeah, but I asked what happens after this warning.
nvm, I'll draft said PR today

**Comment by notRyuk** [comment]
> yeah, but I asked what happens after this warning.

wallpaper wont get added and prompt closes.

**Comment by prem-k-r** [comment]
Please wait for #351 to merge, it will allow you to set higher quality wallpaper too.
