### ISSUE TITLE
The plugin is excellent, why not put it on Google Store

### ISSUE THREAD

**Issue by lanzeweie** [XengShi/materialYouNewTab#31]
I like it very much.

**Comment by XengShi** [comment]
Thanks, I will upload it soon!

**Comment by itz-rj-here** [comment]
It need more modification then he can able to add it to the chrome web store.

**Comment by itz-rj-here** [comment]
@XengShi look on this.

**Comment by Cccc-owo** [comment]
Looking forward

**Comment by XengShi** [comment]
Our extension is now officially available on the Chrome Web Store!
https://chromewebstore.google.com/detail/material-you-newtab/glloabhodjfmeoccmdngmhkpmdlakfbn
