### ISSUE TITLE
Improve code: language.js

### ISSUE THREAD

**Issue by ZiClaud** [XengShi/materialYouNewTab#311]
Instead of having all the languages in a single file, I think it'd be better to have many files, in a directory called `languages`, with in it: `en.json`, `pt.json`, `zh.json`, etc. 
They could also be called: `english.json`, `portuguese.json`, etc.

**Comment by ceskyDJ** [comment]
Related to #158.

**Comment by ZiClaud** [comment]
Missed that, will close now
