### ISSUE TITLE
I can Not able to add Shortcuts in the chome 

### ISSUE THREAD

**Issue by amit9129** [XengShi/materialYouNewTab#320]
I want to add any shortcut for the opening of the any website it . When I have try to add it adds the GitHub of your repository . So please  solving error or isssue in your code

**Comment by amit9129** [comment]
![image](https://github.com/user-attachments/assets/4df888cf-309a-44eb-a2e2-cb0cf5691b75)

**Comment by XengShi** [comment]
You can edit the shortcut names and url
Just tap on url and enter your own url
