### ISSUE TITLE
zoom dragger

### ISSUE THREAD

**Issue by shubham29pathak** [XengShi/materialYouNewTab#328]
when clicking on dragger the text that comes is irritating. either make that visible like the others or disable it totally

**Comment by itz-rj-here** [comment]
@prem-k-r the zoom dragger is removed so can we close it as can't fix?

**Comment by prem-k-r** [comment]
there were some issues with it.. I think we have to fix things and readd the slider.

**Comment by itz-rj-here** [comment]
Wait he already told to totally disable it and now we don't have it as it is removed.

**Comment by itz-rj-here** [comment]
Then closing the issue as completed.

**Comment by prem-k-r** [comment]
> Wait he already told to totally disable it and now we don't have it as it is removed.

the user asked to disable(or always visible) the help text which show up below slider while sliding
we can ignore adding the text when we add back the slider

**Comment by shubham29pathak** [comment]
marked close


right?

**Comment by shubham29pathak** [comment]
cool


but you know whart


i guess user can already use ctrl+mouse wheel to zoom in/out


why we need the dragger?

**Comment by prem-k-r** [comment]
I know, it was added because some users gave feedback that whole UI is large for their device. 
Actually this zoom slider is not present in current Chrome web store v3.0.. you can see 2-3 people asking to add it back lol..
