### ISSUE TITLE
Add more customizabillity

### ISSUE THREAD

**Issue by Juoelenis** [XengShi/materialYouNewTab#33]
Pls

**Comment by PauloStraforini** [comment]
What customizations you'd like to add ??

**Comment by Juoelenis** [comment]
More buttons, rgb slider to choose colors, font changing all kinds of stufd

**Comment by schriftzeichen** [comment]
custom colours, edit weather location, select shortcuts

**Comment by itz-rj-here** [comment]
It's a newly created project. You should wait for more customizabillity. First we need to fix all the issues we are facing on this project.
Thanks.

**Comment by prem-k-r** [comment]
@Juoelenis, please edit the issue to be more specific, such as including options for custom colors. Note that some functionalities have already been implemented.

**Comment by Juoelenis** [comment]
Yea i would like dark mode in the extension, i dont have any

**Comment by itz-rj-here** [comment]
> Yea i would like dark mode in the extension, i dont have any

Dark mode is already included.
![image](https://github.com/user-attachments/assets/449eb6e9-7cf2-4259-b01c-c6ef3a6b96fe)
