### ISSUE TITLE
Digital clock

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#34]
Hi! You extension looks very good! I don't like anolog clock very much since I used to use digital variant. Do you plan support for digital clock, too?

**Comment by raphaelritz** [comment]
That's a great idea, I will work on that and submit a pull request in like a week or whenever I have had time 👍👍

**Comment by XengShi** [comment]
> [haelritz](/raphaelritz)

Hey what about adding this kinda option to access google apps just like native google sites, someone suggest me this and I liked that Idea. We may replace "Ai Tools" buttons with this! 

![gApps](https://github.com/user-attachments/assets/21c2547e-1889-4b48-8726-fd2cdc40e0c0)

**Comment by ceskyDJ** [comment]
> > [haelritz](/raphaelritz)
> 
> Hey what about adding this kinda option to access google apps just like native google sites, someone suggest me this and I liked that Idea. We may replace "Ai Tools" buttons with this! 
> 
> ![gApps](https://github.com/user-attachments/assets/21c2547e-1889-4b48-8726-fd2cdc40e0c0)
> 

The idea looks good. I think it'd be better to have a separate issue for it since it's a little hidden here. What do you think?

**Comment by itz-rj-here** [comment]
It's a great idea fr.

**Comment by Minuga-RC** [comment]
> > [haelritz](/raphaelritz)
> 
> Hey what about adding this kinda option to access google apps just like native google sites, someone suggest me this and I liked that Idea. We may replace "Ai Tools" buttons with this!
> 
> ![gApps](https://private-user-images.githubusercontent.com/48722764/376581623-21c2547e-1889-4b48-8726-fd2cdc40e0c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjMxMDQsIm5iZiI6MTcyOTE2MjgwNCwicGF0aCI6Ii80ODcyMjc2NC8zNzY1ODE2MjMtMjFjMjU0N2UtMTg4OS00YjQ4LTg3MjYtZmQyY2RjNDBlMGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDExMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNzVhY2RhNTM2YzEwY2EwYTc1NmZkY2JmYjRkOWJmYzQ1ODkxNGY1Y2E5NzVkMzliNmY5ZmNiMDRkM2QxNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YxbSqihyQomyaHJ5W2GwQ912FGzae-zMIJoj4H6YhEM)

I could give that a go @itz-rj-here

**Comment by itz-rj-here** [comment]
I would need time. I have exams and assignments to do. :)

**Comment by itz-rj-here** [comment]
Or I have to do it with chatgpt. 😂

**Comment by XengShi** [comment]
@ceskyDJ 
Digital Clock has been added, thanks to @Minuga-RC

**Comment by ceskyDJ** [comment]
@Minuga-RC, thank you very much for your effort ❤️!

**Comment by Minuga-RC** [comment]
Haha actually @XengShi gimme ur telegram or discord I'm willing to put this extension in the chrome web store

**Comment by XengShi** [comment]
> Haha actually @XengShi gimme ur telegram or discord I'm willing to put this extension in the chrome web store 

@XengShi is also my Telegram username! 🙃 I was thinking of uploading the extension to the Chrome Web Store as well. After making a few changes, like adding an option for entering custom locations and a few other features, I will upload it.

**Comment by ceskyDJ** [comment]
Nice to read! Good job, guys. I'm looking forward to the future of this project!

**Comment by Minuga-RC** [comment]
> > Haha actually @XengShi gimme ur telegram or discord I'm willing to put this extension in the chrome web store 
> 
> @XengShi is also my Telegram username! 🙃 I was thinking of uploading the extension to the Chrome Web Store as well. After making a few changes, like adding an option for entering custom locations and a few other features, I will upload it.
> 

Oh I thought you guys weren't uploading it there cuz u guys need to pay fee
