### ISSUE TITLE
[Feature] Support IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [XengShi/materialYouNewTab#342]
Hi there,

Would you like to add support of our service into your project? Our service provided 500 queries per day for keyless query, or 30000 queries per month if you sign up our free plan. You can read more on the result returned via [our documentation](https://www.ip2location.io/ip2location-documentation).

**Comment by XengShi** [comment]
@prem-k-r

**Comment by prem-k-r** [comment]
Thank you for reaching out! I think we’ll stick with ipinfo.io for a bit longer. It’s hard to say no, but we really appreciate your support. We’ll definitely consider your service in the future if we encounter any issues.
