### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#35]
Hello! Do you plan to support more languages for your extension? I'd possibly maintain the Czech translation and help with related localization stuff.

**Comment by XengShi** [comment]
Czech language is added now!

**Comment by ceskyDJ** [comment]
Ah, nice, thanks! I'll look at it and improve the machine learning translation a bit. Btw, could you divide translations to individual files, so I can efectively follow English version for changes?
