### ISSUE TITLE
Default API Key Issue

### ISSUE THREAD

**Issue by KalinduGunathilake** [XengShi/materialYouNewTab#36]
The default API key seems to have an additional '&q' at the end which interferes with the location request.
Although it works fine in the https://www.weatherapi.com/api-explorer.aspx site, it gives the wrong location and weather results in the UI.

- Remove the '&q' part from the default API key and it works just fine.
- Another Suggestion : Call the parsedLocation.city parameter instead of the parsedLocation.ip parameter. Its much accurate in terms of location.

**Comment by Montell2099** [comment]
I'm on Chrome in Windows 10 and the weather doesn't find my location at all, it shows absolutely no weather data. Tried assigning a custom API-key for the problem to hopefully get resolved, but nothing happened. Kind of disappointed in the lack of customizability for an otherwise promising project with a good vision at least.

**Comment by KalinduGunathilake** [comment]
I've got the same issue here too with the API key issue solved in my PR. Just came here to check if anyone else have got it too. The issue seems to be the https://ipapi.co/json is getting a 403 error by CORS or our extension is being blocked by ipapi's CAPTCHA.

Solution
- Use https://ipinfo.io/json/ for the geolocation URL.

**Comment by NikolaiT** [comment]
Just use this API, better data, better free tier:

https://api.ipapi.is/

**Comment by jainam-panchal** [comment]
#42  

Hello!

I have updated the default API key and changed the IP Provider to  https://ipinfo.io/json/ 

@KalinduGunathilake 
We can fetch weather information using the parsedLocation.city parameter, but there are potential issues such as ambiguity in city names. Therefore, I believe it's more reliable to fetch weather data using the ip parameter instead.

**Comment by abdullahdevrel** [comment]
Thanks for using IPinfo. I work here. Ping me if you see any issues with access to our API service. Happy to help!

**Comment by Montell2099** [comment]
> Thanks for using IPinfo. I work here. Ping me if you see any issues with access to our API service. Happy to help!

Haha, what a beautiful coincidence! Thanks for saving the day with a good weather API. it got my location & weather parameters exactly right after the recent update. 👌🏼

> #42
> 
> Hello!
> 
> I have updated the default API key and changed the IP Provider to https://ipinfo.io/json/
> 

Thanks, works great for me right now. Very good UI-presentation for the different stats shown.

Any plans on being able to customize some small areas of the layout to a degree for the user? I would love to be able to move around those widget-looking info-boxes up the order, and closer to the UI-top. Also move up the, during the summer and/or depending on where you live.

Thanks for getting it to work! It's looking good.

**Comment by KalinduGunathilake** [comment]
Thank you everyone!
