### ISSUE TITLE
feature request:ADD RANDOM COLOUR OPTION

### ISSUE THREAD

**Issue by CholexMax** [XengShi/materialYouNewTab#360]
ADD RANDOM COLOUR FEATURES WHICH HELP USER TO SELECT RANDOM COLOUR BY ONE CLICK AND IT CAN REFLECT IN UI

**Comment by itz-rj-here** [comment]
@prem-k-r is it already added ig.

**Comment by prem-k-r** [comment]
no, probably he meant random theme color, not wallpaper

**Comment by itz-rj-here** [comment]
ohh...

**Comment by CholexMax** [comment]
yes you are right i exactly mean that

**Comment by prem-k-r** [comment]
I don't know if it's a good idea.. I mean personally most of the random theme colors won't looks good.. depends on personal preference

**Comment by CholexMax** [comment]
YOU ARE RIGHT AS SOME TIME LATER I NOTICED THAT PART 〽️

**Comment by prem-k-r** [comment]
> YOU ARE RIGHT AS SOME TIME LATER I NOTICED THAT PART 〽️

ok, so closing the issue
