### ISSUE TITLE
Weather not working 

### ISSUE THREAD

**Issue by nguyenhailongmeowmeow** [XengShi/materialYouNewTab#368]
![image](https://github.com/user-attachments/assets/b9dd6236-fe5c-4d36-9d1e-1168e38f8f55)
![image](https://github.com/user-attachments/assets/fae665a1-5f04-4cd5-93db-2284f8f614b3)

**Comment by prem-k-r** [comment]
Hi @nguyenhailongmeowmeow please enter your own WeatherAPI key
www.xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html

**Comment by prem-k-r** [comment]
Only paste the api key, no need for full website.. 
Like `c6bcsh577fhut57212`

**Comment by prem-k-r** [comment]
Btw, nice wallpaper of Furina :)

**Comment by nguyenhailongmeowmeow** [comment]
still not work btw
![image](https://github.com/user-attachments/assets/c2473852-1029-4127-9e4f-9f992c49056c)
![image](https://github.com/user-attachments/assets/85d6a754-4f49-4727-bf91-91999734176d)
and https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html it inaccessible
![Uploading image.png…]()

**Comment by prem-k-r** [comment]
> Only paste the api key, no need for full website.. Like `c6bcsh577fhut57212`

This one was invalid.. i wrote randomly lol

**Comment by prem-k-r** [comment]
You can read text of html here
https://github.com/XengShi/materialYouNewTab/blob/main/docs/Get_WeatherAPI_Key.html

**Comment by nguyenhailongmeowmeow** [comment]
it work btw 
no 1 furina lover <3333
![Screenshot 2024-12-24 143035](https://github.com/user-attachments/assets/de6e9d1b-b1ee-4a23-9f1c-35668dce847d)

**Comment by Anasarfeen123** [comment]
> Hi @nguyenhailongmeowmeow please enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
Can you please automate this?

**Comment by nguyenhailongmeowmeow** [comment]
it fixed 5 days ago :D
bruh

**Comment by prem-k-r** [comment]
> > please enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
> 
> Can you please automate this?

wdym, like how? please explain

**Comment by nguyenhailongmeowmeow** [comment]
https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html

**Comment by itz-rj-here** [comment]
> > > please enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
> > 
> > 
> > Can you please automate this?
> 
> wdym, like how? please explain

Mybe he is asking for making the api adds automatically 🙂
Which is not even possible.

**Comment by Anasarfeen123** [comment]
> > > > please enter your own WeatherAPI key [xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)
> > > 
> > > 
> > > Can you please automate this?
> > 
> > 
> > wdym, like how? please explain
> 
> Mybe he is asking for making the api adds automatically 🙂 Which is not even possible.

I meant to get the location of the user and then putting that city name to the api. Instead of manually putting and generating my own api, make it like server (I dont have too much background on this, but i saw some websites do this).

**Comment by itz-rj-here** [comment]
@prem-k-r can you check this. My brain stopped working 🗿

**Comment by Anasarfeen123** [comment]
> @prem-k-r can you check this. My brain stopped working 🗿

nevermind, weather bug got fixed automatically. Thanks!

**Comment by prem-k-r** [comment]
> I meant to get the location of the user and then putting that city name to the api. Instead of manually putting and generating my own api, make it like server (I dont have too much background on this, but i saw some websites do this).


generating api key doesn't require city name or location. You just need to Sign up with any email.

currently we have hard coded 10 weatherapi's api keys.. server can be used here.. we put api keys in server.. but then the extension will be dependent on it, we wont be doing it, it poses privacy concern too. right now you can run the extension locally.

**Comment by prem-k-r** [comment]
> > @prem-k-r can you check this. My brain stopped working 🗿
> 
> nevermind, weather bug got fixed automatically. Thanks!

actually not, 8/10 api keys have reached limit for this month, 
we highly recommend to generate your own key.. will take only 2-3 min

**Comment by itz-rj-here** [comment]
Closing this issue as completed
