### ISSUE TITLE
WEBSITE MATERIAL NEWTAB ISSUE IN FIREFOX

### ISSUE THREAD

**Issue by DimasGitHubOfficial** [XengShi/materialYouNewTab#372]
LOOK WHY IS THE COLOR ONLY LIKE THAT-
![Screenshot 2024-12-25 095150](https://github.com/user-attachments/assets/b2237c53-d009-4c7a-835e-3304a86aa479)

**Comment by DimasGitHubOfficial** [comment]
hello anyone there?

**Comment by XengShi** [comment]
> hello anyone there?

Thanks for reporting the issue, I noticed that in the chrome-store branch and fixed.

**Comment by XengShi** [comment]
![image](https://github.com/user-attachments/assets/27f213ee-7906-41fb-b203-76baec80d931)
@prem-k-r

**Comment by prem-k-r** [comment]
#371 will most likely fixes this
