### ISSUE TITLE
add seconds in digital clock pls

### ISSUE THREAD

**Issue by DimasGitHubOfficial** [XengShi/materialYouNewTab#374]
i made this new feature
![add seconds in digital clock](https://github.com/user-attachments/assets/f85b1fcf-2595-4f84-9a1b-e916f906ea56)

**Comment by DimasGitHubOfficial** [comment]
- [V ] add new feature

**Comment by DimasGitHubOfficial** [comment]
huh?????

**Comment by XengShi** [comment]
> huh?????

Sorry but I think this is kinda useless, and the analogue clock already shows seconds

**Comment by XengShi** [comment]
Ohh sorry I thought you were requesting this feature if you have already added the feature that's great but enhance the UI, align seconds to the next line and decrease its size.
