### ISSUE TITLE
yes i live in earth

### ISSUE THREAD

**Issue by DimasGitHubOfficial** [XengShi/materialYouNewTab#397]
![Screenshot 2024-12-28 130913](https://github.com/user-attachments/assets/bfa000b8-72f4-4e7b-90bc-bb701aef7dac)

**Comment by prem-k-r** [comment]
![image](https://github.com/user-attachments/assets/46f34a12-f5b6-48f4-973f-098ee8d88a6a)
**If the weather functionality isn't working**

**Comment by prem-k-r** [comment]
please enter your own WeatherAPI key
[xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html](https://xengshi.github.io/materialYouNewTab/docs/Get_WeatherAPI_Key.html)

**Comment by DimasGitHubOfficial** [comment]
it works
