### ISSUE TITLE
"Waxing Crescent" the only "widget"-style element missing an icon & it's not a link, for further info-card redirection

### ISSUE THREAD

**Issue by Montell2099** [XengShi/materialYouNewTab#44]
![Screenshot_20241010-005531](https://github.com/user-attachments/assets/06f6461d-df00-42f2-9864-d6ddae4bb886)

**Comment by KalinduGunathilake** [comment]
Is this related to this repo?

**Comment by Montell2099** [comment]
> Is this related to this repo?

Haha, shit I'm tired. My bad, thanks for the heads up.
