### ISSUE TITLE
Language choose have problem

### ISSUE THREAD

**Issue by weiyi88** [XengShi/materialYouNewTab#45]
When I chose to switch the language, it did not switch. Every time I refreshed, it was still English.
Secondly, the language translation is also incomplete.

**Comment by MestreWalla** [comment]
I'm working and studying and a little short on time because I leave at 7:00 and arrive at 23:00, on the weekend I'll be fixing these problems.

**Comment by MestreWalla** [comment]
The language is fixed and completed.

**Comment by itz-rj-here** [comment]
#48
