### ISSUE TITLE
The geolocation provider appears inactive, causing inaccuracies in determining the user's location.

### ISSUE THREAD

**Issue by rediahmds** [XengShi/materialYouNewTab#5]
It seems that the `geolocation-db.com/json/` service is currently inactive. As of the time of writing this message, it only returns:

```json
{
    "country_code": "Not found",
    "country_name": "Not found",
    "city": "Not found",
    "postal": "Not found",
    "latitude": "Not found",
    "longitude": "Not found",
    "IPv4": "Not found",
    "state": "Not found"
}
```

**Comment by MudassirS0hail** [comment]
has this been fixed?

**Comment by rediahmds** [comment]
I fixed it in my PR. But, it seems like the owner hasn't merged it yet.

**Comment by MudassirS0hail** [comment]
Upon restarting it worked for me, but the second I restart the browser it goes back.
Now it's stuck at Earth lol:
[image](https://github.com/user-attachments/assets/cb436423-e83f-416e-bce8-74285d05b22d)

**Comment by Asifali2o** [comment]
If the geolocation-db.com/json/ service is returning "Not found" for all fields, it may be temporarily down or discontinued. First, check the service status online to confirm. If it's unavailable, switch to an alternative geolocation API such as ipstack, ipinfo.io, or ipgeolocation.io, which provide similar data. Additionally, update your code to handle "Not found" responses gracefully by showing an error message or using another service. Monitoring the status of geolocation-db.com will help you switch back if the [service](https://www.styleanma.com/) becomes available again.

**Comment by abdullahdevrel** [comment]
Let me know if you have any questions about using [IPinfo](https://ipinfo.io) for the project. Without an access token, we can support up to 1,000 requests per day.

**Comment by itz-rj-here** [comment]
Already Fixed.

**Comment by itz-rj-here** [comment]
@XengShi Close this. Its fixed.
