### ISSUE TITLE
Persistent Dark Theme Alert on Every New Tab Open

### ISSUE THREAD

**Issue by venkat2305** [XengShi/materialYouNewTab#51]
When selecting the dark mode in the Material You NewTab extension, an alert pops up with the message:

> ![image](https://github.com/user-attachments/assets/41906762-12a9-496f-a345-7fa49882736b)

While it's acceptable to see this alert once, the issue arises when this same alert appears **every time** a new tab is opened. 

**Expected Behavior:**
- The alert should appear **only once** after switching to dark mode.

**Actual Behavior:**
- The alert pops up on **every** new tab, causing a repetitive user experience.

Please fix this behavior so that the alert shows only once when dark mode is selected.

**Comment by itz-rj-here** [comment]
Hi there. The dark mode isn't finished yet. You are viewing this message because of this. However, someone in #52 has just set up a new dark mode. After the latest update, if everything appears good and the owner agrees, you won't see this notification.

**Comment by itz-rj-here** [comment]
@XengShi Close this. Its fixed.
