### ISSUE TITLE
中文显示有问题，没有保存选项，会自动变到英文

### ISSUE THREAD

**Issue by im-dashan** [XengShi/materialYouNewTab#56]
中文显示有问题，没有保存选项，会自动变到英文，并且汉化不完全，希望可以加入到各大主流浏览器的商店方便下载

**Comment by prem12321kumar** [comment]
@im-dashan added, can you confirm if all Chinese translations are correct. 
Please mention the inaccurate ones, if needed to change.

**Comment by prem-k-r** [comment]
@XengShi please close
