### ISSUE TITLE
UI error in Search box

### ISSUE THREAD

**Issue by prem12321kumar** [XengShi/materialYouNewTab#66]
When searching from dropdown autofill suggestion (from history) in 'Your Query' placeholder, the search icon partially covered.
![image](https://github.com/user-attachments/assets/03effb25-b90d-4e43-8ef1-498431e318f2)
![image](https://github.com/user-attachments/assets/751b955b-5c39-41ef-94a0-8972d2a3888c)
Expected:
![image](https://github.com/user-attachments/assets/3007598f-13ac-42a9-961f-1e9e3118235f)

Can we just remove this autofill suggestion

**Comment by itz-rj-here** [comment]
Already Fixed. #65 
Thanks for the information.
