### ISSUE TITLE
Arrow doesn't work in AI Tools

### ISSUE THREAD

**Issue by prem12321kumar** [XengShi/materialYouNewTab#67]
when clicking down arrow from AI Tools menu, it does nothing. Probably it should hide back the menu and show shortcuts
![image](https://github.com/user-attachments/assets/b1573e0b-e3b6-4396-bfe3-2fefc8d9e16e)
![image](https://github.com/user-attachments/assets/fa576001-ae1a-4c9f-bb04-6d4d3b191671)
![image](https://github.com/user-attachments/assets/58811b15-8bcc-4110-b8a7-893d5fd4fde7)

Expected:
![image](https://github.com/user-attachments/assets/5afc1dfc-a0b6-4fc0-9405-f1e9495d14d4)

**Comment by itz-rj-here** [comment]
Huh thats weird. I just saw that now. Didn't noticed it earlier.
@prem12321kumar Thanks to inform. We will remove it on the next further update.

**Comment by itz-rj-here** [comment]
@Minuga-RC can you check it?..

**Comment by Minuga-RC** [comment]
> @Minuga-RC can you check it?..

alr

**Comment by itz-rj-here** [comment]
Fixed.
