### ISSUE TITLE
New language translation confirmation needed.

### ISSUE THREAD

**Issue by itz-rj-here** [XengShi/materialYouNewTab#68]

**Comment by itz-rj-here** [comment]
@MestreWalla Can you kindly fix all the issues i told you about the translates?

**Comment by MestreWalla** [comment]
I'll work on it this weekend, as I said in another topic, I work and study so I'm from 7:00 to 23:00 from Monday to Friday without being able to do anything.

**Comment by MestreWalla** [comment]
I'll work on it this weekend, as I said in another topic, I work and study so I'm from 7:00 to 23:00 from Monday to Friday without being able to do anything.

**Comment by itz-rj-here** [comment]
Okay great. But i think someone has done your work 4 u.

**Comment by itz-rj-here** [comment]
#72

**Comment by prem12321kumar** [comment]
I did some work.
Left to do which I may attempt later, or someone else can handle it.:
1. "menuCloseButton:hover::after": "Close"
![image](https://github.com/user-attachments/assets/283e5902-eaba-4c95-984f-b7c4d95b9348)

2.  Good Morning/Afternoon/Evening/Night in Digital Clock (and maybe weekday too)
![image](https://github.com/user-attachments/assets/1a6dc51b-fea3-4f91-b055-aba2ebc880a4)

3. "Humidity" when idle, that is When Location=Earth. (When offline or can't fetch weather)
![image](https://github.com/user-attachments/assets/7c8738fd-41ed-42c0-8724-692991215109)

4. Remaining translations for other languages, excluding Hindi.

**Comment by itz-rj-here** [comment]
Hmm. Let me check it.

**Comment by ceskyDJ** [comment]
If you activate the digital clock, it looks like the days of the week aren't localized (use the correct translation string):
![image](https://github.com/user-attachments/assets/1e74ab47-e77d-44eb-a10e-700f678b2ff5)

**Comment by ceskyDJ** [comment]
One other thing is you display the name of the month and day of the week wrong for Czech:
![image](https://github.com/user-attachments/assets/03cf002a-ae3a-4a44-86ed-dad894e74413)

The correct form (if you want to use shortcuts) is: Ne, 20. říj.
Or maybe use the full version for Czech: Neděle, 20. října (it's up to you, of course).

**Comment by ceskyDJ** [comment]
There is a problem with "Pocitová teplota" ("Feels like" in English), which is too long but a correct translation so that the background may be extended a bit.

**Comment by prem12321kumar** [comment]
> One other thing is you display the name of the month and day of the week wrong for Czech: ![image](https://private-user-images.githubusercontent.com/48548230/378209575-03cf002a-ae3a-4a44-86ed-dad894e74413.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDU1MDAsIm5iZiI6MTcyOTQ0NTIwMCwicGF0aCI6Ii80ODU0ODIzMC8zNzgyMDk1NzUtMDNjZjAwMmEtYWUzYS00YTQ0LTg2ZWQtZGFkODk0ZTc0NDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE3MjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTkwYTM3MzcxZjkwMGNmZDIxZmNiZjMxODk3MmQ3YWJmNmY4MTRhMmVhNWU1MzkwZTlhMmVmMTRmMWIyM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n0_JKfVWdpccVhXbhXT-FKSZYhJAwMBQ5JCIgjXxgvk)
> 
> The correct form (if you want to use shortcuts) is: Ne, 20. říj. Or maybe use the full version for Czech: Neděle, 20. října (it's up to you, of course).


I will correct it tomorrow

**Comment by prem12321kumar** [comment]
> There is a problem with "Pocitová teplota" ("Feels like" in English), which is too long but a correct translation so that the background may be extended a bit.

#89

**Comment by prem12321kumar** [comment]
> One other thing is you display the name of the month and day of the week wrong for Czech: ![image](https://private-user-images.githubusercontent.com/48548230/378209575-03cf002a-ae3a-4a44-86ed-dad894e74413.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjQ1MTMsIm5iZiI6MTcyOTUyNDIxMywicGF0aCI6Ii80ODU0ODIzMC8zNzgyMDk1NzUtMDNjZjAwMmEtYWUzYS00YTQ0LTg2ZWQtZGFkODk0ZTc0NDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE1MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZGM4OWJlNjlkOWM4MjYyMTVhZjMzY2RkMTBkMGUxNTg2YTgzMjA0ZDIwMWU1ODBiNmQyZTgwZGMxOTAzNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4BNA3O__svvsqniYGQPNWAYbdKom7Tv6A0ypivOijUA)
> 
> The correct form (if you want to use shortcuts) is: Ne, 20. říj. Or maybe use the full version for Czech: Neděle, 20. října (it's up to you, of course).

#98 done, Pondělí, 21. října for today

**Comment by ceskyDJ** [comment]
Do you know if this is still relevant? I think this has already been solved. @itz-rj-here, could you please check it out?

**Comment by prem-k-r** [comment]
There are some texts that need to be translated other than for in Hindi, Bangla, and Czech. Based on recent changes, updates are needed for greetings and the textbox toggle. Currently, these texts fall back to English.
Additionally, some translations may need adjustments to align with the original English text in other languages.

**Comment by prem-k-r** [comment]
> There are some texts that need to be translated other than for in Hindi, Bangla, and Czech. Based on recent changes, updates are needed for greetings and the textbox toggle. Currently, these texts fall back to English. Additionally, some translations may need adjustments to align with the original English text in other languages.

zh: @Guy-Berryman 
it: @ZiClaud 
tr: @Nobody9512 
ru: @giwih 
vi: @diepdp-kaiyouit 

Guys please check, thanks

**Comment by ceskyDJ** [comment]
> There are some texts that need to be translated other than for in Hindi, Bangla, and Czech. Based on recent changes, updates are needed for greetings and the textbox toggle. Currently, these texts fall back to English.
> Additionally, some translations may need adjustments to align with the original English text in other languages.
> 
> 

Oh, I see.

**Comment by itz-rj-here** [comment]
> Do you know if this is still relevant? I think this has already been solved. @itz-rj-here, could you please check it out? 

I have exams ongoing. I will come here when i get some time only. After the exams i will be active again. But until you have to talk to @prem-k-r for issues or other things. 
And @prem-k-r said right. Some translations aren't being added. So when all the translations are done this issue will be closed as finished.

**Comment by MestreWalla** [comment]
portuguese is updated now.

**Comment by itz-rj-here** [comment]
> portuguese is updated now.

Great. Thanks for the check.

**Comment by prem-k-r** [comment]
"Shortcut icons will appear round" is it correct. It is more like Shortcut icons will be smaller..  I'm not sure. 
![IMG_20241103_183423](https://github.com/user-attachments/assets/2eca9bf5-4787-444f-8854-5f8830c692de)

**Comment by itz-rj-here** [comment]
> "Shortcut icons will appear round" is it correct. It is more like Shortcut icons will be smaller.. I'm not sure. ![IMG_20241103_183423](https://private-user-images.githubusercontent.com/60751338/382573311-2eca9bf5-4787-444f-8854-5f8830c692de.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mzk4MzYsIm5iZiI6MTczMDYzOTUzNiwicGF0aCI6Ii82MDc1MTMzOC8zODI1NzMzMTEtMmVjYTliZjUtNDc4Ny00NDRmLTg4NTQtNWY4ODMwYzY5MmRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEzMTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NWMyZjk5Zjk3NzQzMGFmZTJkZGEwOWFlMWY1ZWFkMTk0MjZjMTQ2NjFlYzQ4MzEyN2I5ODExODNhNGFkNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hl4o-eljA-8LYHViKSu-KKbr85fOy0BlFEh81qG1orw)

You are kind of right with that. It is the shortcut icons will be smaller. Additionally, It only works when using extra or custom shortcuts.

**Comment by ceskyDJ** [comment]
> "Shortcut icons will appear round" is it correct. It is more like Shortcut icons will be smaller.. I'm not sure.

I thought about it, too, but I don't know exactly how it works.

**Comment by itz-rj-here** [comment]
@prem-k-r r all the translation are done? If yes then i will close this issue.

**Comment by prem-k-r** [comment]
> @prem-k-r r all the translation are done? If yes then i will close this issue.

I think Hindi, Bangla, Czech, Turkish, Uzbek done

Russian and Portuguese are pending in PR. Other languages have some missing text. Also it may need to update some translations to align with the original English text for accuracy.

**Comment by itz-rj-here** [comment]
> > @prem-k-r r all the translation are done? If yes then i will close this issue.
> 
> I think Hindi, Bangla, Czech, Turkish, Uzbek done
> 
> Russian and Portuguese are pending in PR. Other languages have some missing text. Also it may need to update some translations to align with the original English text for accuracy.

Fine then i will keep this issue open.

**Comment by itz-rj-here** [comment]
uhh still the issue is open 🥲

**Comment by prem-k-r** [comment]
> uhh still the issue is open 🥲

Close it
