### ISSUE TITLE
Analog clock problem

### ISSUE THREAD

**Issue by prem12321kumar** [XengShi/materialYouNewTab#75]
https://github.com/user-attachments/assets/7fcf92ef-d496-457e-b11c-6fce0c6c9f9d

steps to reproduce:
1. turn on digital clock
2. use 12 hr format
3. turn off digital clock

**Comment by XengShi** [comment]
@kerogs

**Comment by kerogs** [comment]
Normally this should work if the page is launched (or relaunched) with the desired format. i think it's because the clock only synchronizes once when the page is launched.

**Comment by itz-rj-here** [comment]
Me and @Minuga-RC is working with that.

**Comment by Minuga-RC** [comment]
Wait what I fixed that tho by only updating the clock if the tab is focused

**Comment by prem12321kumar** [comment]
Probably first time launch glitched. Not happening anymore.
