### ISSUE TITLE
Search suggestions don't seem to be working

### ISSUE THREAD

**Issue by prem12321kumar** [XengShi/materialYouNewTab#79]

**Comment by itz-rj-here** [comment]
We meed some proof or some details for that. Can you please include it.

**Comment by ceskyDJ** [comment]
I think it doesn't work almost anywhere unless you turn on the CORS bypassing feature. It works for me, when I turn on the bypass via default proxy but not at all without it.

**Comment by prem12321kumar** [comment]
> I think it doesn't work almost anywhere unless you turn on the CORS bypassing feature. It works for me, when I turn on the bypass via default proxy but not at all without it.

Yes correct, earlier it was working with turning on proxy in Chrome. Now need to turn on proxy to show suggestions.

**Comment by ceskyDJ** [comment]
> > I think it doesn't work almost anywhere unless you turn on the CORS bypassing feature. It works for me, when I turn on the bypass via default proxy but not at all without it.
> 
> Yes correct, earlier it was working without turning on proxy in Chrome. Now need to turn on proxy to show suggestions.

So, maybe let's turn proxying automatically with suggestions + give it a clear description saying the user needs to use a proxy for bypassing CORS?

**Comment by prem12321kumar** [comment]
> > I think it doesn't work almost anywhere unless you turn on the CORS bypassing feature. It works for me, when I turn on the bypass via default proxy but not at all without it.
> 
> Yes correct, earlier it was working without turning on proxy in Chrome. Now need to turn on proxy to show suggestions.

@itz-rj-here is it the default behavior, if so.. can close the issue

**Comment by itz-rj-here** [comment]
Yeah

> > > I think it doesn't work almost anywhere unless you turn on the CORS bypassing feature. It works for me, when I turn on the bypass via default proxy but not at all without it.
> > 
> > 
> > Yes correct, earlier it was working without turning on proxy in Chrome. Now need to turn on proxy to show suggestions.
> 
> @itz-rj-here is it the default behavior, if so.. can close the issue

**Comment by XengShi** [comment]
@itz-rj-here  hello

**Comment by itz-rj-here** [comment]
> @itz-rj-here hello

Hiii @XengShi. Looks like you guys are working great and I got too many works today. Tomorrow is my final class in the school. :( After the last school our school life will be finished.
I am kinda sad also happy, like 2 in 1.
