### ISSUE TITLE
Colors on search bar and others on "Dark Theme" 

### ISSUE THREAD

**Issue by deibs11** [XengShi/materialYouNewTab#8]
Hey there! I recently got this add-on (Firefox).

I have a suggestion, which you may have contemplated by this time but:

- On **"Dark Theme"**, it'd be good to put the text on the Search Bar on white color.

![Screenshot from 2024-08-23 18-28-38](https://github.com/user-attachments/assets/f2185bac-e8ff-426a-a8b9-5f82d61da8c5)

**Comment by Abhishekq10** [comment]
And also disable the alert saying `under development` on every reload of the tab

**Comment by deibs11** [comment]
Yes, that also has some issues, sadly I ended up stopping using that, maybe I'll give it another try.

**Comment by itz-rj-here** [comment]
Fixed #52
