### ISSUE TITLE
I can't have empty text on the place of "Double tap to edit"

### ISSUE THREAD

**Issue by ceskyDJ** [XengShi/materialYouNewTab#85]
Removing the default text "Double tap to edit" doesn't survive the page reload.

How to reproduce:

1. Open a new tab with this extension installed without changes.
2. Double tap (or click) on "Double tap to edit."
3. Remove all the text from there.
4. Refresh the page.
5. The default text "Double tap to edit" remains.

**Comment by XengShi** [comment]
I think we made this as a feature 🤣

**Comment by ceskyDJ** [comment]
I see how you mean it. But there is no way for hiding/removing the text. Could you add an option for it or something?

**Comment by itz-rj-here** [comment]
Huhhh. Need to think what we can do.

**Comment by prem12321kumar** [comment]
@ceskyDJ Just add a space. It should appears like empty and won't be refreshed back.

**Comment by ceskyDJ** [comment]
> @ceskyDJ Just add a space. It should appears like empty and won't be refreshed back.

Thanks, it sounds like a good workout. But as you want to publish it to the store, it should have some "basic user" way, too. I think a config option could solve it well.

**Comment by prem12321kumar** [comment]
#120 
Added toggle to show/hide UserTextBox

**Comment by ceskyDJ** [comment]
Nice! I think we can close this after merge.

**Comment by prem12321kumar** [comment]
@ceskyDJ some untranslated texts to translate in Czech, also some changes in English ones
