### ISSUE TITLE
weather app not working in firefox 129.0.2

### ISSUE THREAD

**Issue by soninikul007** [XengShi/materialYouNewTab#9]
Hello, 
I have made a new api key and added to the extension but the weather is not working properly. PLease help.

**Comment by theoneand33** [comment]
Same here

**Comment by SalahGhafari** [comment]
I'm having the same issue, please help.

**Comment by itz-rj-here** [comment]
This issue is fixed in the #42 .

**Comment by itz-rj-here** [comment]
@XengShi Close this. Its fixed.
