### ISSUE TITLE
Weather Display issue when weatherTextCondition is long

### ISSUE THREAD

**Issue by prem12321kumar** [XengShi/materialYouNewTab#97]
![image](https://github.com/user-attachments/assets/fa958567-e2a2-4827-809b-d61fe6c8f11a)
![image](https://github.com/user-attachments/assets/959b8b07-79f9-4423-84b5-485dffd45382)

btw, for me weatherAPI always fetch wrong location from IPv4 address. Reason why I use manual inputted location. 😅

**Comment by XengShi** [comment]
![Screenshot from 2024-10-22 21-03-58](https://github.com/user-attachments/assets/e14b57fd-36e3-4238-ad83-04b97a86d5fe)

After changing the language getting Undefined location and empty Feels like temp

**Comment by prem12321kumar** [comment]
@XengShi merge #86 to fix it

**Comment by prem12321kumar** [comment]
@XengShi, also could you please check and merge the other functional PRs at your convenience?

#104: script.js file (languages.js and index.js have already been merged)

#98 and #99: Czech date formatting

And display PR #89 (confirm if this view is acceptable)

Also, PR #93 is good to go.
Thanks

**Comment by XengShi** [comment]
Everything seems perfect now.
@prem12321kumar Bhai bahut achha kaam kiya hai aapne, tomorrow I will release it

**Comment by prem12321kumar** [comment]
Thanks a lot! I am learning a lot with all of this.

**Comment by XengShi** [comment]
Hey, what do you think about translating the greeting messages (like Good Morning, Good Evening, etc.) into regional languages? Since you've already worked on similar tasks, I understand it may not offer much in terms of learning something new. If you're interested, feel free to work on it only when you have some free time!

**Comment by prem12321kumar** [comment]
> Hey, what do you think about translating the greeting messages (like Good Morning, Good Evening, etc.) into regional languages? Since you've already worked on similar tasks, I understand it may not offer much in terms of learning something new. If you're interested, feel free to work on it only when you have some free time!

Actually, I did try it, but there was bugs. I put it on hold and planned to try again later.
I was also working on translating numerals in some languages like Bengali, and fallback to English if the translation was missing for any particular language. None of it was working properly. Maybe in comming weeks or so, if I can correct it and not solved by anyone else till then, I'll raise a request for a pull merge.

**Comment by prem12321kumar** [comment]
I was checking my fork to ensure everything was fine and found some unwanted things
![image](https://github.com/user-attachments/assets/f85b5082-7999-444e-b94c-508212579aad)
This alert should be translated as well or not, not sure. Thoughts?

![image](https://github.com/user-attachments/assets/885e306c-4b70-470b-b0e6-540571536058)
In Bangla this translation is bit longer, should we translate it to just নিজের প্রক্সি হোস্ট করুন (Host your proxy) instead of 'Host your own proxy'?

and the change I did in userText to remove placeholder text when the user starts editing and restore placeholder if the user leaves it empty after clicking, It works for English only as placeholder text "Click here to edit" is hardcoded in the focus and blur event listeners.

**Comment by itz-rj-here** [comment]
>In Bangla this translation is bit longer, should we translate it to just নিজের প্রক্সি হোস্ট করুন (Host your proxy) instead of 'Host your own proxy'?
> 
> and the change I did in userText to remove placeholder text when the user starts editing and restore placeholder if the user leaves it empty after clicking, It works for English only as placeholder text "Click here to edit" is hardcoded in the focus and blur event listeners.

You are good to go with that. It should be নিজের প্রক্সি হোস্ট করুন.

**Comment by prem12321kumar** [comment]
> Hey, what do you think about translating the greeting messages (like Good Morning, Good Evening, etc.) into regional languages? Since you've already worked on similar tasks, I understand it may not offer much in terms of learning something new. If you're interested, feel free to work on it only when you have some free time!

finally done. lol the issue was in index.html, reordered language.js and script.js
